-- 0058_audit_logs.sql
-- The audit trail behind /super/logs.
--
-- The screen showed five hardcoded lines — "Failed login attempts (5)" from
-- 203.0.113.42, an invoice generated by "billing-bot" — the same five for
-- every viewer, on every day, since the day they were typed. An audit trail
-- that is fiction is worse than none: it is the screen someone will open when
-- they need to know who changed something.
--
-- This logs writes in the DATABASE rather than in the API, and that is the
-- whole point. A trigger cannot be gone around: a change made through
-- /api/v1, through the Supabase SQL editor, by a script with the service key
-- or by a policy-bypassing function all land here the same way. Logging in the
-- route handlers would only ever record the writes that went through the
-- route handlers.
--
-- What is recorded is METADATA, not payloads: who, when, which table, which
-- row, and which columns changed. Not the values — copying every patient's
-- chart and every payslip into a second table that every super admin can read
-- across all tenants would create a bigger exposure than it audits. The
-- exception is a short list of platform and content tables carrying no
-- personal data, where the before and after are the useful part; they are
-- named in the attach loop at the bottom.

create type public.audit_action as enum ('insert', 'update', 'delete');

create table public.audit_logs (
  -- identity, not uuid: this is append-only and will be the largest table in
  -- the database. A monotonic key also gives "in the order it happened" for
  -- free when two events share a timestamp.
  id bigint generated always as identity primary key,

  occurred_at timestamptz not null default now(),

  /**
   * Who. Snapshots, deliberately — the same reasoning as an invoice: an audit
   * row states who did something on a date, and a deleted account must not
   * quietly become "unknown" across five years of history. That is also why
   * there is no foreign key to profiles.
   */
  actor_id    uuid,
  actor_email text,
  actor_role  text,

  -- Null for a change made with the service key or in the SQL editor: there
  -- is no user behind those, and inventing one would be a lie.

  /**
   * Which hospital, by id and by the name it had at the time.
   *
   * The name is copied for the same reason the actor's email is, and there is
   * deliberately no foreign key to `tenants`: an audit row must outlive the
   * thing it describes. A reference would either block deleting a hospital or
   * cascade its history away with it, and both are worse than a stale name.
   * The trail is self-contained, and reading it joins nothing.
   */
  tenant_id   uuid,
  tenant_name text,

  table_name  text not null,
  record_id   uuid,
  action      public.audit_action not null,

  -- Update only. `updated_at` is stripped: every update touches it, so it says
  -- nothing, and leaving it in makes every row look like something changed.
  changed_fields text[] not null default '{}',

  -- Old and new values, and only for the tables named at the bottom of this
  -- file. Null everywhere else.
  details jsonb
);

create index audit_logs_occurred_at_idx on public.audit_logs (occurred_at desc);
create index audit_logs_table_idx       on public.audit_logs (table_name, occurred_at desc);
create index audit_logs_actor_idx       on public.audit_logs (actor_id, occurred_at desc);
create index audit_logs_tenant_idx      on public.audit_logs (tenant_id, occurred_at desc);
create index audit_logs_record_idx      on public.audit_logs (record_id);

-- ---------------------------------------------------------------- rls ---
-- Read: super_admin only. Write: nobody. There is no insert, update or delete
-- policy on purpose, so no client can forge an entry or erase one — not even a
-- super admin. The trigger below writes as the table's owner, which is how a
-- log stays a log.

alter table public.audit_logs enable row level security;

create policy audit_logs_super_read on public.audit_logs
  for select to authenticated
  using (public.is_super_admin());

-- ------------------------------------------------------------ trigger ---

create or replace function public.audit_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old      jsonb := case when tg_op = 'INSERT' then '{}'::jsonb else to_jsonb(old) end;
  v_new      jsonb := case when tg_op = 'DELETE' then '{}'::jsonb else to_jsonb(new) end;
  v_changed  text[] := '{}';
  v_record   uuid;
  v_tenant   uuid;
  v_tenant_name text;
  v_details  jsonb;
  v_claims   jsonb;
begin
  if tg_op = 'UPDATE' then
    select coalesce(array_agg(k.key order by k.key), '{}')
      into v_changed
      from jsonb_each(v_new) as k(key, value)
     where k.key <> 'updated_at'
       and v_old -> k.key is distinct from v_new -> k.key;

    -- A no-op update. Saving a form without changing anything is not an event,
    -- and logging it buries the ones that are.
    if array_length(v_changed, 1) is null then
      return null;
    end if;
  end if;

  begin
    v_record := coalesce(v_new ->> 'id', v_old ->> 'id')::uuid;
  exception when others then
    -- A table not keyed by a uuid. The row is still logged, without a target.
    v_record := null;
  end;

  begin
    v_tenant := coalesce(v_new ->> 'tenant_id', v_old ->> 'tenant_id')::uuid;
  exception when others then
    v_tenant := null;
  end;

  -- current_setting rather than auth.jwt(), so this never raises when there is
  -- no request context at all — a migration, a psql session, a cron job.
  v_claims := nullif(current_setting('request.jwt.claims', true), '')::jsonb;

  v_tenant := coalesce(v_tenant, nullif(v_claims ->> 'tenant_id', '')::uuid);

  if v_tenant is not null then
    -- One primary-key lookup. Null when the hospital is the thing being
    -- deleted, which is honest: by then there is no name to record.
    if tg_table_name = 'tenants' then
      v_tenant_name := coalesce(v_new ->> 'name', v_old ->> 'name');
    else
      select t.name into v_tenant_name from public.tenants t where t.id = v_tenant;
    end if;
  end if;

  if tg_argv[0] = 'values' then
    v_details := jsonb_build_object('old', v_old, 'new', v_new);
  end if;

  insert into public.audit_logs (
    actor_id, actor_email, actor_role, tenant_id, tenant_name,
    table_name, record_id, action, changed_fields, details
  )
  values (
    nullif(v_claims ->> 'sub', '')::uuid,
    nullif(v_claims ->> 'email', ''),
    nullif(v_claims ->> 'user_role', ''),
    v_tenant,
    v_tenant_name,
    tg_table_name,
    v_record,
    lower(tg_op)::public.audit_action,
    v_changed,
    v_details
  );

  return null; -- after trigger
end;
$$;

-- Not an API. PostgREST publishes every function in `public`, so this one is
-- taken back off it; the triggers call it regardless.
revoke all on function public.audit_row() from public, anon, authenticated;

/**
 * Puts the trigger on one table. A function rather than 48 hand-written
 * create-triggers, for the same reason apply_tenant_rls exists: the next
 * module adds one line instead of copying a block that will drift.
 *
 * p_log_values turns on old/new capture. Say yes only for tables with no
 * personal data on them — see the note at the top of this file.
 */
create or replace function public.attach_audit(p_table regclass, p_log_values boolean default false)
returns void
language plpgsql
set search_path = ''
as $$
begin
  execute format('drop trigger if exists audit_log on %s', p_table);
  execute format(
    'create trigger audit_log after insert or update or delete on %s '
    'for each row execute function public.audit_row(%L)',
    p_table,
    case when p_log_values then 'values' else 'names' end
  );
end;
$$;

-- A migration helper, not an endpoint. PostgREST would otherwise publish it at
-- /rest/v1/rpc/attach_audit for anyone signed in.
revoke all on function public.attach_audit(regclass, boolean) from public, anon, authenticated;

comment on function public.attach_audit(regclass, boolean) is
  'Attaches the audit trigger to a table. New modules call this in their migration; see docs/module-guide.md.';

-- ------------------------------------------------------------- attach ---
-- Every table in `public`, with two exceptions: audit_logs itself, which would
-- log its own logging forever, and nothing else. The secrets tables ARE
-- audited — that a hospital admin's password was replaced is exactly the kind
-- of thing this screen exists to show — and since values are never captured
-- for them, the secret does not follow.

do $$
declare
  r record;
  -- Platform and content tables: no personal data, and the before/after is the
  -- useful part when someone asks what a setting used to say.
  with_values constant text[] := array[
    'global_settings', 'roles', 'packages', 'offers', 'hospital_packages',
    'platform_invoices', 'tenants', 'cms_pages', 'cms_blog_posts', 'announcements'
  ];
begin
  for r in
    select c.oid::regclass as tbl, c.relname as name
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and c.relkind = 'r'
       and c.relname <> 'audit_logs'
     order by c.relname
  loop
    perform public.attach_audit(r.tbl, r.name = any(with_values));
  end loop;
end $$;
