-- 0094_investigations.sql
-- The list of investigations — lab tests, imaging, cardiac and other
-- workups — a doctor picks from on the prescription pad.
--
-- The pad's Investigation section was a free-text box: "Lipid Profile" typed
-- by hand, spelt however the doctor spelt it that day. Now it searches this
-- list as they type, and a test that isn't on it can still be typed in.
--
-- 1,047 standard investigations in 10 categories, from the standard library a
-- Bangladeshi prescription tool ships (prescriply.bd's Library, read on
-- 2026-09-16): test names only, which are the common names of the tests.
--
-- A global lookup like specialties (0093): the same for every hospital.
-- Signed-in users read it — the doctor's pad is where it is used — and only
-- the super admin writes.

create table public.investigations (
  id         uuid primary key default gen_random_uuid(),
  name       text not null
               constraint investigations_name_check check (length(btrim(name)) between 1 and 200),
  -- "Clinical Biochemistry", "Imaging & Cardiac Investigations", ...
  category   text,
  -- Lower first. Ties fall back to the name.
  sort_order integer not null default 0,
  -- Hidden from the pad's picker; prescriptions that already name it keep it.
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index investigations_name_key on public.investigations (lower(btrim(name)));
create index investigations_category_idx on public.investigations (category);

create trigger investigations_set_updated_at
  before update on public.investigations
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- RLS ---

alter table public.investigations enable row level security;

create policy investigations_select on public.investigations
  for select to authenticated
  using (true);

create policy investigations_write on public.investigations
  for all to authenticated
  using (public.is_super_admin())
  with check (public.is_super_admin());

-- No personal data, so the old and new values are kept too.
select public.attach_audit('public.investigations', true);

comment on table public.investigations is
  'Investigations a doctor picks from on the prescription pad (0094). A global lookup; the super admin edits it.';

-- --------------------------------------------------------------- the list ---

insert into public.investigations (category, name) values
  ('Clinical Biochemistry', '2 Hours After Breakfast Blood Sugar (2HABF)'),
  ('Clinical Biochemistry', '24 Hour Urinary Protein'),
  ('Clinical Biochemistry', '5'' Nucleotidase'),
  ('Clinical Biochemistry', 'Adenosine Deaminase (ADA)'),
  ('Clinical Biochemistry', 'Albumin Globulin Ratio (A/G Ratio)'),
  ('Clinical Biochemistry', 'Anion Gap'),
  ('Clinical Biochemistry', 'Apolipoprotein A1 (Apo A1)'),
  ('Clinical Biochemistry', 'Apolipoprotein B (Apo B)'),
  ('Clinical Biochemistry', 'Arterial Blood Gas (ABG)'),
  ('Clinical Biochemistry', 'Arterial Blood Gas Analysis (ABG)'),
  ('Clinical Biochemistry', 'B-type Natriuretic Peptide (BNP)'),
  ('Clinical Biochemistry', 'Blood Urea'),
  ('Clinical Biochemistry', 'Blood Urea Nitrogen (BUN)'),
  ('Clinical Biochemistry', 'C-Reactive Protein (CRP)'),
  ('Clinical Biochemistry', 'Ceruloplasmin'),
  ('Clinical Biochemistry', 'Creatine Kinase MB (CK-MB)'),
  ('Clinical Biochemistry', 'Creatine Phosphokinase (CPK)'),
  ('Clinical Biochemistry', 'Creatinine Clearance (CrCl)'),
  ('Clinical Biochemistry', 'CSF Chloride'),
  ('Clinical Biochemistry', 'CSF Glucose'),
  ('Clinical Biochemistry', 'CSF Lactate'),
  ('Clinical Biochemistry', 'CSF Protein'),
  ('Clinical Biochemistry', 'Cystatin C'),
  ('Clinical Biochemistry', 'Estimated Glomerular Filtration Rate (eGFR)'),
  ('Clinical Biochemistry', 'Fasting Blood Sugar (FBS)'),
  ('Clinical Biochemistry', 'Fasting Lipid Profile (Lipid Profile)'),
  ('Clinical Biochemistry', 'Fructosamine'),
  ('Clinical Biochemistry', 'Gamma Glutamyl Transferase (GGT)'),
  ('Clinical Biochemistry', 'Glucose Challenge Test (GCT)'),
  ('Clinical Biochemistry', 'Glucose in CSF (CSF Glucose)'),
  ('Clinical Biochemistry', 'Glycated Hemoglobin (HbA1c)'),
  ('Clinical Biochemistry', 'HDL Cholesterol'),
  ('Clinical Biochemistry', 'High Sensitivity C-Reactive Protein (hs-CRP)'),
  ('Clinical Biochemistry', 'High Sensitivity Troponin (hs-Troponin)'),
  ('Clinical Biochemistry', 'LDL Cholesterol'),
  ('Clinical Biochemistry', 'Lipid Profile'),
  ('Clinical Biochemistry', 'Lipoprotein (a)'),
  ('Clinical Biochemistry', 'Liver Function Test (LFT)'),
  ('Clinical Biochemistry', 'Microalbuminuria'),
  ('Clinical Biochemistry', 'Myoglobin'),
  ('Clinical Biochemistry', 'N-Terminal pro B-type Natriuretic Peptide (NT-proBNP)'),
  ('Clinical Biochemistry', 'Non-HDL Cholesterol'),
  ('Clinical Biochemistry', 'Oral Glucose Tolerance Test (OGTT)'),
  ('Clinical Biochemistry', 'Protein in CSF (CSF Protein)'),
  ('Clinical Biochemistry', 'Random Blood Sugar (RBS)'),
  ('Clinical Biochemistry', 'Red Cell Folate'),
  ('Clinical Biochemistry', 'Serum Albumin'),
  ('Clinical Biochemistry', 'Serum Aldolase'),
  ('Clinical Biochemistry', 'Serum Alkaline Phosphatase (ALP)'),
  ('Clinical Biochemistry', 'Serum Ammonia'),
  ('Clinical Biochemistry', 'Serum Amylase'),
  ('Clinical Biochemistry', 'Serum Angiotensin Converting Enzyme (ACE)'),
  ('Clinical Biochemistry', 'Serum Bicarbonate (HCO3)'),
  ('Clinical Biochemistry', 'Serum Bile Acids'),
  ('Clinical Biochemistry', 'Serum Bilirubin'),
  ('Clinical Biochemistry', 'Serum Calcium (Ca)'),
  ('Clinical Biochemistry', 'Serum Chloride (Cl)'),
  ('Clinical Biochemistry', 'Serum Copper'),
  ('Clinical Biochemistry', 'Serum Creatinine'),
  ('Clinical Biochemistry', 'Serum Electrolytes'),
  ('Clinical Biochemistry', 'Serum Ferritin'),
  ('Clinical Biochemistry', 'Serum Globulin'),
  ('Clinical Biochemistry', 'Serum Glutamic Oxaloacetic Transaminase (SGOT)'),
  ('Clinical Biochemistry', 'Serum Glutamic Pyruvic Transaminase (SGPT)'),
  ('Clinical Biochemistry', 'Serum Ionized Calcium'),
  ('Clinical Biochemistry', 'Serum Iron'),
  ('Clinical Biochemistry', 'Serum Lactate'),
  ('Clinical Biochemistry', 'Serum Lactate Dehydrogenase (LDH)'),
  ('Clinical Biochemistry', 'Serum Lead'),
  ('Clinical Biochemistry', 'Serum Lipase'),
  ('Clinical Biochemistry', 'Serum Magnesium (Mg)'),
  ('Clinical Biochemistry', 'Serum Osmolality'),
  ('Clinical Biochemistry', 'Serum Phosphate'),
  ('Clinical Biochemistry', 'Serum Potassium (K)'),
  ('Clinical Biochemistry', 'Serum Pyruvate'),
  ('Clinical Biochemistry', 'Serum Selenium'),
  ('Clinical Biochemistry', 'Serum Sodium (Na)'),
  ('Clinical Biochemistry', 'Serum Total Cholesterol'),
  ('Clinical Biochemistry', 'Serum Total Protein'),
  ('Clinical Biochemistry', 'Serum Triglycerides (TG)'),
  ('Clinical Biochemistry', 'Serum Uric Acid'),
  ('Clinical Biochemistry', 'Serum Zinc'),
  ('Clinical Biochemistry', 'Sweat Chloride Test'),
  ('Clinical Biochemistry', 'Total Iron Binding Capacity (TIBC)'),
  ('Clinical Biochemistry', 'Transferrin'),
  ('Clinical Biochemistry', 'Troponin I (cTnI)'),
  ('Clinical Biochemistry', 'Troponin T (cTnT)'),
  ('Clinical Biochemistry', 'Unsaturated Iron Binding Capacity (UIBC)'),
  ('Clinical Biochemistry', 'Urine Osmolality'),
  ('Clinical Biochemistry', 'Urine Protein Creatinine Ratio (UPCR)'),
  ('Clinical Biochemistry', 'Venous Blood Gas (VBG)'),
  ('Clinical Biochemistry', 'VLDL Cholesterol'),
  ('Clinical Pathology & Body Fluids', '24 Hours Urinary Total Protein (24h Urine Protein)'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary 17-Hydroxycorticosteroids'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary 17-Ketosteroids'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary 5-HIAA'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Aldosterone'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Calcium'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Citrate'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Copper'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Homovanillic Acid (HVA)'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Magnesium'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Microalbumin'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Oxalate'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Phosphate'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Potassium'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Sodium'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Total Protein'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Urea'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary Uric Acid'),
  ('Clinical Pathology & Body Fluids', '24-hour Urinary VMA'),
  ('Clinical Pathology & Body Fluids', '72-hour Fecal Fat'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid Adenosine Deaminase (Ascitic ADA)'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid Amylase'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid Cell Count'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid for AFB'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid for Malignant Cells (Cytology)'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid Glucose'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid LDH'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid Protein'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid Routine Examination'),
  ('Clinical Pathology & Body Fluids', 'Ascitic Fluid Study (Ascitic Fluid)'),
  ('Clinical Pathology & Body Fluids', 'Body Fluid Adenosine Deaminase (Fluid ADA)'),
  ('Clinical Pathology & Body Fluids', 'Body Fluid Cell Count'),
  ('Clinical Pathology & Body Fluids', 'Body Fluid for Malignant Cells (Cytology)'),
  ('Clinical Pathology & Body Fluids', 'Cerebrospinal Fluid Routine Examination (CSF R/E)'),
  ('Clinical Pathology & Body Fluids', 'Cerebrospinal Fluid Study (CSF Study)'),
  ('Clinical Pathology & Body Fluids', 'CSF Adenosine Deaminase (CSF ADA)'),
  ('Clinical Pathology & Body Fluids', 'CSF Cell Count and Cytology'),
  ('Clinical Pathology & Body Fluids', 'CSF Culture and Sensitivity'),
  ('Clinical Pathology & Body Fluids', 'CSF for AFB'),
  ('Clinical Pathology & Body Fluids', 'CSF Gram Stain'),
  ('Clinical Pathology & Body Fluids', 'CSF India Ink Preparation'),
  ('Clinical Pathology & Body Fluids', 'CSF LDH'),
  ('Clinical Pathology & Body Fluids', 'CSF Oligoclonal Bands'),
  ('Clinical Pathology & Body Fluids', 'CSF VDRL'),
  ('Clinical Pathology & Body Fluids', 'Fecal Calprotectin'),
  ('Clinical Pathology & Body Fluids', 'Fecal Elastase-1'),
  ('Clinical Pathology & Body Fluids', 'Fecal Fat (Sudan III Stain)'),
  ('Clinical Pathology & Body Fluids', 'Fecal Immunochemical Test (FIT)'),
  ('Clinical Pathology & Body Fluids', 'Pericardial Fluid Cytology'),
  ('Clinical Pathology & Body Fluids', 'Pericardial Fluid Study (Pericardial Fluid)'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid Adenosine Deaminase (Pleural ADA)'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid Amylase'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid for AFB'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid for Malignant Cells (Cytology)'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid Glucose'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid LDH'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid pH'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid Protein'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid Routine Examination'),
  ('Clinical Pathology & Body Fluids', 'Pleural Fluid Study (Pleural Fluid)'),
  ('Clinical Pathology & Body Fluids', 'Post-Vasectomy Semen Analysis'),
  ('Clinical Pathology & Body Fluids', 'Semen Analysis'),
  ('Clinical Pathology & Body Fluids', 'Seminal Fluid Fructose'),
  ('Clinical Pathology & Body Fluids', 'Serum-Ascites Albumin Gradient (SAAG)'),
  ('Clinical Pathology & Body Fluids', 'Spot Urine Calcium-Creatinine Ratio'),
  ('Clinical Pathology & Body Fluids', 'Spot Urine Chloride'),
  ('Clinical Pathology & Body Fluids', 'Spot Urine Potassium'),
  ('Clinical Pathology & Body Fluids', 'Spot Urine Sodium'),
  ('Clinical Pathology & Body Fluids', 'Stool for AFB'),
  ('Clinical Pathology & Body Fluids', 'Stool for Cryptosporidium'),
  ('Clinical Pathology & Body Fluids', 'Stool for Giardia Antigen'),
  ('Clinical Pathology & Body Fluids', 'Stool for H. pylori Antigen'),
  ('Clinical Pathology & Body Fluids', 'Stool for Occult Blood Test (OBT)'),
  ('Clinical Pathology & Body Fluids', 'Stool for Ova and Parasites'),
  ('Clinical Pathology & Body Fluids', 'Stool for Reducing Substance'),
  ('Clinical Pathology & Body Fluids', 'Stool pH'),
  ('Clinical Pathology & Body Fluids', 'Stool Routine and Microscopic Examination (Stool R/M/E)'),
  ('Clinical Pathology & Body Fluids', 'Synovial Fluid Cell Count'),
  ('Clinical Pathology & Body Fluids', 'Synovial Fluid for Crystals'),
  ('Clinical Pathology & Body Fluids', 'Synovial Fluid Study (Synovial Fluid)'),
  ('Clinical Pathology & Body Fluids', 'Urine Albumin Creatinine Ratio (ACR)'),
  ('Clinical Pathology & Body Fluids', 'Urine Delta-Aminolevulinic Acid (Delta-ALA)'),
  ('Clinical Pathology & Body Fluids', 'Urine for AFB'),
  ('Clinical Pathology & Body Fluids', 'Urine for Albumin'),
  ('Clinical Pathology & Body Fluids', 'Urine for Bence Jones Protein (BJP)'),
  ('Clinical Pathology & Body Fluids', 'Urine for Bile Salt and Bile Pigment'),
  ('Clinical Pathology & Body Fluids', 'Urine for Chyle (Chyluria)'),
  ('Clinical Pathology & Body Fluids', 'Urine for Eosinophils'),
  ('Clinical Pathology & Body Fluids', 'Urine for Hemosiderin'),
  ('Clinical Pathology & Body Fluids', 'Urine for Ketone Bodies'),
  ('Clinical Pathology & Body Fluids', 'Urine for Malignant Cells (Urine Cytology)'),
  ('Clinical Pathology & Body Fluids', 'Urine for Microalbumin'),
  ('Clinical Pathology & Body Fluids', 'Urine for Porphobilinogen'),
  ('Clinical Pathology & Body Fluids', 'Urine for Porphyrins'),
  ('Clinical Pathology & Body Fluids', 'Urine for Pregnancy Test (UPT)'),
  ('Clinical Pathology & Body Fluids', 'Urine for Reducing Substances'),
  ('Clinical Pathology & Body Fluids', 'Urine for Schistosoma Ova'),
  ('Clinical Pathology & Body Fluids', 'Urine for Sugar'),
  ('Clinical Pathology & Body Fluids', 'Urine for Urobilinogen'),
  ('Clinical Pathology & Body Fluids', 'Urine Gram Stain'),
  ('Clinical Pathology & Body Fluids', 'Urine Microalbumin'),
  ('Clinical Pathology & Body Fluids', 'Urine Myoglobin'),
  ('Clinical Pathology & Body Fluids', 'Urine pH'),
  ('Clinical Pathology & Body Fluids', 'Urine Pregnancy Test (UPT)'),
  ('Clinical Pathology & Body Fluids', 'Urine Routine and Microscopic Examination (Urine R/M/E)'),
  ('Clinical Pathology & Body Fluids', 'Urine Specific Gravity'),
  ('Endocrinology & Hormones', '1,25-Dihydroxy Vitamin D (Calcitriol)'),
  ('Endocrinology & Hormones', '11-Deoxycortisol'),
  ('Endocrinology & Hormones', '17-Hydroxypregnenolone'),
  ('Endocrinology & Hormones', '17-Hydroxyprogesterone (17-OHP)'),
  ('Endocrinology & Hormones', '24-hour Urinary Catecholamines'),
  ('Endocrinology & Hormones', '24-hour Urinary Free Cortisol (UFC)'),
  ('Endocrinology & Hormones', '24-hour Urinary Metanephrines'),
  ('Endocrinology & Hormones', '24-hour Urinary Vanillylmandelic Acid (VMA)'),
  ('Endocrinology & Hormones', '5-Hydroxyindoleacetic Acid (5-HIAA)'),
  ('Endocrinology & Hormones', 'Adrenocorticotropic Hormone (ACTH)'),
  ('Endocrinology & Hormones', 'Aldosterone (Serum)'),
  ('Endocrinology & Hormones', 'Aldosterone-to-Renin Ratio (ARR)'),
  ('Endocrinology & Hormones', 'Androstenedione'),
  ('Endocrinology & Hormones', 'Anti-Mullerian Hormone (AMH)'),
  ('Endocrinology & Hormones', 'Anti-Müllerian Hormone (AMH)'),
  ('Endocrinology & Hormones', 'Anti-Thyroglobulin Antibody (Anti-Tg)'),
  ('Endocrinology & Hormones', 'Anti-Thyroid Peroxidase Antibody (Anti-TPO)'),
  ('Endocrinology & Hormones', 'Antidiuretic Hormone (ADH)'),
  ('Endocrinology & Hormones', 'Beta Human Chorionic Gonadotropin (Beta-hCG)'),
  ('Endocrinology & Hormones', 'Beta-CrossLaps (CTX)'),
  ('Endocrinology & Hormones', 'Bioavailable Testosterone'),
  ('Endocrinology & Hormones', 'Bone-specific Alkaline Phosphatase'),
  ('Endocrinology & Hormones', 'C-Peptide'),
  ('Endocrinology & Hormones', 'Calcitonin'),
  ('Endocrinology & Hormones', 'Captopril Challenge Test'),
  ('Endocrinology & Hormones', 'Chromogranin A (CgA)'),
  ('Endocrinology & Hormones', 'Copeptin'),
  ('Endocrinology & Hormones', 'Dehydroepiandrosterone (DHEA)'),
  ('Endocrinology & Hormones', 'Dehydroepiandrosterone Sulfate (DHEA-S)'),
  ('Endocrinology & Hormones', 'Dihydrotestosterone (DHT)'),
  ('Endocrinology & Hormones', 'Direct Renin Concentration (DRC)'),
  ('Endocrinology & Hormones', 'Erythropoietin (EPO)'),
  ('Endocrinology & Hormones', 'Estrone (E1)'),
  ('Endocrinology & Hormones', 'Fasting Serum Insulin'),
  ('Endocrinology & Hormones', 'Follicle Stimulating Hormone (FSH)'),
  ('Endocrinology & Hormones', 'Free Testosterone'),
  ('Endocrinology & Hormones', 'Free Thyroxine (FT4)'),
  ('Endocrinology & Hormones', 'Free Triiodothyronine (FT3)'),
  ('Endocrinology & Hormones', 'Gastrin'),
  ('Endocrinology & Hormones', 'Glucagon'),
  ('Endocrinology & Hormones', 'Glucagon Stimulation Test'),
  ('Endocrinology & Hormones', 'Glutamic Acid Decarboxylase Antibody (Anti-GAD)'),
  ('Endocrinology & Hormones', 'Growth Hormone (GH)'),
  ('Endocrinology & Hormones', 'Growth Hormone Suppression Test'),
  ('Endocrinology & Hormones', 'Human Placental Lactogen (hPL)'),
  ('Endocrinology & Hormones', 'Inhibin A'),
  ('Endocrinology & Hormones', 'Inhibin B'),
  ('Endocrinology & Hormones', 'Insulin Autoantibody (IAA)'),
  ('Endocrinology & Hormones', 'Insulin Tolerance Test (ITT)'),
  ('Endocrinology & Hormones', 'Insulin-like Growth Factor 1 (IGF-1)'),
  ('Endocrinology & Hormones', 'Insulin-like Growth Factor Binding Protein 3 (IGFBP-3)'),
  ('Endocrinology & Hormones', 'Islet Cell Antibody (ICA)'),
  ('Endocrinology & Hormones', 'Late-night Salivary Cortisol'),
  ('Endocrinology & Hormones', 'Leptin'),
  ('Endocrinology & Hormones', 'Luteinizing Hormone (LH)'),
  ('Endocrinology & Hormones', 'Macroprolactin'),
  ('Endocrinology & Hormones', 'Osteocalcin'),
  ('Endocrinology & Hormones', 'Overnight Dexamethasone Suppression Test'),
  ('Endocrinology & Hormones', 'Parathyroid Hormone (PTH)'),
  ('Endocrinology & Hormones', 'Parathyroid Hormone-related Peptide (PTHrP)'),
  ('Endocrinology & Hormones', 'Plasma Catecholamines'),
  ('Endocrinology & Hormones', 'Plasma Free Metanephrines'),
  ('Endocrinology & Hormones', 'Plasma Renin Activity (PRA)'),
  ('Endocrinology & Hormones', 'Pregnenolone'),
  ('Endocrinology & Hormones', 'Procollagen Type 1 N-Terminal Propeptide (P1NP)'),
  ('Endocrinology & Hormones', 'Proinsulin'),
  ('Endocrinology & Hormones', 'Reverse Triiodothyronine (rT3)'),
  ('Endocrinology & Hormones', 'Serotonin'),
  ('Endocrinology & Hormones', 'Serum Cortisol'),
  ('Endocrinology & Hormones', 'Serum Estradiol (E2)'),
  ('Endocrinology & Hormones', 'Serum Progesterone'),
  ('Endocrinology & Hormones', 'Serum Prolactin (PRL)'),
  ('Endocrinology & Hormones', 'Serum Testosterone'),
  ('Endocrinology & Hormones', 'Serum Vitamin D (25-OH Vitamin D)'),
  ('Endocrinology & Hormones', 'Sex Hormone Binding Globulin (SHBG)'),
  ('Endocrinology & Hormones', 'Short Synacthen Test (ACTH Stimulation Test)'),
  ('Endocrinology & Hormones', 'Thyroid Peroxidase Antibody (Anti-TPO)'),
  ('Endocrinology & Hormones', 'Thyroid Stimulating Hormone (TSH)'),
  ('Endocrinology & Hormones', 'Thyroxine Binding Globulin (TBG)'),
  ('Endocrinology & Hormones', 'Total Thyroxine (T4)'),
  ('Endocrinology & Hormones', 'Total Triiodothyronine (T3)'),
  ('Endocrinology & Hormones', 'TSH Receptor Antibody (TRAb)'),
  ('Endocrinology & Hormones', 'Unconjugated Estriol (E3)'),
  ('Endocrinology & Hormones', 'Water Deprivation Test'),
  ('Hematology & Coagulation', 'ABO and Rh Blood Grouping'),
  ('Hematology & Coagulation', 'Absolute Basophil Count'),
  ('Hematology & Coagulation', 'Absolute Eosinophil Count (AEC)'),
  ('Hematology & Coagulation', 'Absolute Lymphocyte Count (ALC)'),
  ('Hematology & Coagulation', 'Absolute Monocyte Count (AMC)'),
  ('Hematology & Coagulation', 'Absolute Neutrophil Count (ANC)'),
  ('Hematology & Coagulation', 'Absolute Reticulocyte Count (ARC)'),
  ('Hematology & Coagulation', 'Activated Partial Thromboplastin Time (APTT)'),
  ('Hematology & Coagulation', 'Activated Protein C Resistance (APC-R)'),
  ('Hematology & Coagulation', 'Anti-Beta-2 Glycoprotein I Antibody'),
  ('Hematology & Coagulation', 'Anti-Factor Xa Assay (Anti-Xa)'),
  ('Hematology & Coagulation', 'Antibody Screening (Indirect Antiglobulin)'),
  ('Hematology & Coagulation', 'Anticardiolipin Antibody (aCL)'),
  ('Hematology & Coagulation', 'Antithrombin III (AT-III)'),
  ('Hematology & Coagulation', 'Autohemolysis Test'),
  ('Hematology & Coagulation', 'BCR-ABL1 (Philadelphia Chromosome)'),
  ('Hematology & Coagulation', 'Beta-Thalassemia Mutation Analysis'),
  ('Hematology & Coagulation', 'Bleeding Time (BT)'),
  ('Hematology & Coagulation', 'Blood Film for Malarial Parasite (MP)'),
  ('Hematology & Coagulation', 'Blood Grouping and Rh Typing'),
  ('Hematology & Coagulation', 'Bone Marrow Cytogenetics (Karyotyping)'),
  ('Hematology & Coagulation', 'Bone Marrow Study'),
  ('Hematology & Coagulation', 'Bone Marrow Trephine Biopsy'),
  ('Hematology & Coagulation', 'Buffy Coat Examination'),
  ('Hematology & Coagulation', 'Capillary Fragility Test (Hess Test)'),
  ('Hematology & Coagulation', 'Clot Retraction Time'),
  ('Hematology & Coagulation', 'Clotting Time (CT)'),
  ('Hematology & Coagulation', 'Coagulation Factor II Assay (Prothrombin)'),
  ('Hematology & Coagulation', 'Coagulation Factor IX Assay'),
  ('Hematology & Coagulation', 'Coagulation Factor V Assay'),
  ('Hematology & Coagulation', 'Coagulation Factor VII Assay'),
  ('Hematology & Coagulation', 'Coagulation Factor VIII Assay'),
  ('Hematology & Coagulation', 'Coagulation Factor X Assay'),
  ('Hematology & Coagulation', 'Coagulation Factor XI Assay'),
  ('Hematology & Coagulation', 'Coagulation Factor XII Assay'),
  ('Hematology & Coagulation', 'Coagulation Factor XIII Assay'),
  ('Hematology & Coagulation', 'Coagulation Mixing Study'),
  ('Hematology & Coagulation', 'Complete Blood Count (CBC)'),
  ('Hematology & Coagulation', 'Complete Blood Count with Peripheral Blood Film (CBC with PBF)'),
  ('Hematology & Coagulation', 'Cross Matching'),
  ('Hematology & Coagulation', 'D-dimer'),
  ('Hematology & Coagulation', 'Differential Count of WBC (DC)'),
  ('Hematology & Coagulation', 'Differential Leucocyte Count (DLC)'),
  ('Hematology & Coagulation', 'Direct Coombs Test (DCT)'),
  ('Hematology & Coagulation', 'Erythrocyte Sedimentation Rate (ESR)'),
  ('Hematology & Coagulation', 'Euglobulin Clot Lysis Time (ECLT)'),
  ('Hematology & Coagulation', 'Factor V Leiden Mutation'),
  ('Hematology & Coagulation', 'Factor VIII Inhibitor Assay (Bethesda)'),
  ('Hematology & Coagulation', 'Fetal Hemoglobin (HbF)'),
  ('Hematology & Coagulation', 'Fibrin Degradation Products (FDP)'),
  ('Hematology & Coagulation', 'Fibrinogen'),
  ('Hematology & Coagulation', 'Flow Cytometry Immunophenotyping (Leukemia/Lymphoma)'),
  ('Hematology & Coagulation', 'G6PD Screening'),
  ('Hematology & Coagulation', 'Ham''s Acidified Serum Test'),
  ('Hematology & Coagulation', 'Haptoglobin'),
  ('Hematology & Coagulation', 'Heinz Body Preparation'),
  ('Hematology & Coagulation', 'Hematocrit (HCT)'),
  ('Hematology & Coagulation', 'Hemoglobin (Hb)'),
  ('Hematology & Coagulation', 'Hemoglobin A2 (HbA2)'),
  ('Hematology & Coagulation', 'Hemoglobin Electrophoresis (Hb Electrophoresis)'),
  ('Hematology & Coagulation', 'Hemoglobin H Inclusion Body Test'),
  ('Hematology & Coagulation', 'Hemoglobin HPLC'),
  ('Hematology & Coagulation', 'Heparin-Induced Thrombocytopenia Antibody (Anti-PF4)'),
  ('Hematology & Coagulation', 'Homocysteine'),
  ('Hematology & Coagulation', 'Indirect Coombs Test (ICT)'),
  ('Hematology & Coagulation', 'International Normalized Ratio (INR)'),
  ('Hematology & Coagulation', 'JAK2 V617F Mutation'),
  ('Hematology & Coagulation', 'LE Cell Preparation'),
  ('Hematology & Coagulation', 'LE Cell Test'),
  ('Hematology & Coagulation', 'Leukocyte Alkaline Phosphatase Score (LAP)'),
  ('Hematology & Coagulation', 'Lupus Anticoagulant (LA)'),
  ('Hematology & Coagulation', 'Mean Corpuscular Hemoglobin (MCH)'),
  ('Hematology & Coagulation', 'Mean Corpuscular Hemoglobin Concentration (MCHC)'),
  ('Hematology & Coagulation', 'Mean Corpuscular Volume (MCV)'),
  ('Hematology & Coagulation', 'Mean Platelet Volume (MPV)'),
  ('Hematology & Coagulation', 'Methemoglobin Level'),
  ('Hematology & Coagulation', 'NESTROFT (Naked Eye Single Tube Red Cell Osmotic Fragility Test)'),
  ('Hematology & Coagulation', 'Osmotic Fragility Test (OFT)'),
  ('Hematology & Coagulation', 'Paroxysmal Nocturnal Hemoglobinuria Flow Cytometry (PNH by CD55/CD59)'),
  ('Hematology & Coagulation', 'Peripheral Blood Film (PBF)'),
  ('Hematology & Coagulation', 'Perls'' Prussian Blue Iron Stain (Marrow)'),
  ('Hematology & Coagulation', 'Platelet Aggregation Study'),
  ('Hematology & Coagulation', 'Platelet Count'),
  ('Hematology & Coagulation', 'Platelet Distribution Width (PDW)'),
  ('Hematology & Coagulation', 'Plateletcrit (PCT)'),
  ('Hematology & Coagulation', 'Protein C'),
  ('Hematology & Coagulation', 'Protein S'),
  ('Hematology & Coagulation', 'Prothrombin G20210A Mutation'),
  ('Hematology & Coagulation', 'Prothrombin Time (PT)'),
  ('Hematology & Coagulation', 'Pyruvate Kinase Assay (PK)'),
  ('Hematology & Coagulation', 'Red Cell Distribution Width (RDW)'),
  ('Hematology & Coagulation', 'Reptilase Time'),
  ('Hematology & Coagulation', 'Reticulocyte Count'),
  ('Hematology & Coagulation', 'Reticulocyte Hemoglobin Content (Ret-He)'),
  ('Hematology & Coagulation', 'Rh (D) Typing'),
  ('Hematology & Coagulation', 'Sickling Test'),
  ('Hematology & Coagulation', 'Sucrose Lysis Test'),
  ('Hematology & Coagulation', 'Thrombin Time (TT)'),
  ('Hematology & Coagulation', 'Total Count of RBC (TC RBC)'),
  ('Hematology & Coagulation', 'Total Count of WBC (TC WBC)'),
  ('Hematology & Coagulation', 'Total Red Blood Cell Count (RBC Count)'),
  ('Hematology & Coagulation', 'Total White Blood Cell Count (TWBC)'),
  ('Hematology & Coagulation', 'Transferrin Saturation'),
  ('Hematology & Coagulation', 'von Willebrand Factor Activity (Ristocetin Cofactor)'),
  ('Hematology & Coagulation', 'von Willebrand Factor Antigen (vWF:Ag)'),
  ('Histopathology & Cytology', 'Alcian Blue Stain'),
  ('Histopathology & Cytology', 'ALK Immunohistochemistry'),
  ('Histopathology & Cytology', 'Ascitic Fluid Cytology'),
  ('Histopathology & Cytology', 'Bcl-2 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Bone Biopsy'),
  ('Histopathology & Cytology', 'Breast Biopsy'),
  ('Histopathology & Cytology', 'Bronchial Biopsy'),
  ('Histopathology & Cytology', 'Bronchoalveolar Lavage Cytology (BAL Cytology)'),
  ('Histopathology & Cytology', 'Buccal Smear'),
  ('Histopathology & Cytology', 'Calretinin Immunohistochemistry'),
  ('Histopathology & Cytology', 'Carcinoembryonic Antigen (CEA) Immunostain'),
  ('Histopathology & Cytology', 'CD10 Immunohistochemistry'),
  ('Histopathology & Cytology', 'CD117 (c-KIT) Immunohistochemistry'),
  ('Histopathology & Cytology', 'CD15 Immunohistochemistry'),
  ('Histopathology & Cytology', 'CD20 Immunohistochemistry'),
  ('Histopathology & Cytology', 'CD3 Immunohistochemistry'),
  ('Histopathology & Cytology', 'CD30 Immunohistochemistry'),
  ('Histopathology & Cytology', 'CD34 Immunohistochemistry'),
  ('Histopathology & Cytology', 'CD4/CD8 T-Cell Subset by Flow Cytometry'),
  ('Histopathology & Cytology', 'CDX2 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Cell Block Preparation'),
  ('Histopathology & Cytology', 'Cerebrospinal Fluid Cytology (CSF Cytology)'),
  ('Histopathology & Cytology', 'Cervical Biopsy'),
  ('Histopathology & Cytology', 'Chromogenic In Situ Hybridization (CISH)'),
  ('Histopathology & Cytology', 'Chromogranin A Immunohistochemistry'),
  ('Histopathology & Cytology', 'CK7 / CK20 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Colonic Biopsy'),
  ('Histopathology & Cytology', 'Cone Biopsy of Cervix'),
  ('Histopathology & Cytology', 'Congo Red Stain for Amyloid'),
  ('Histopathology & Cytology', 'Cyclin D1 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Cytokeratin Immunostain (CK)'),
  ('Histopathology & Cytology', 'Cytology of Body Fluid (Fluid Cytology)'),
  ('Histopathology & Cytology', 'Desmin Immunohistochemistry'),
  ('Histopathology & Cytology', 'Dilatation and Curettage (D&C)'),
  ('Histopathology & Cytology', 'Direct Immunofluorescence of Skin'),
  ('Histopathology & Cytology', 'DNA Ploidy Analysis'),
  ('Histopathology & Cytology', 'Duodenal Biopsy'),
  ('Histopathology & Cytology', 'EBV-Encoded RNA In Situ Hybridization (EBER)'),
  ('Histopathology & Cytology', 'Electron Microscopy of Tissue'),
  ('Histopathology & Cytology', 'Endocervical Curettage (ECC)'),
  ('Histopathology & Cytology', 'Endometrial Biopsy'),
  ('Histopathology & Cytology', 'Endoscopic Biopsy'),
  ('Histopathology & Cytology', 'Epithelial Membrane Antigen (EMA)'),
  ('Histopathology & Cytology', 'Esophageal Biopsy'),
  ('Histopathology & Cytology', 'Estrogen Receptor / Progesterone Receptor (ER/PR)'),
  ('Histopathology & Cytology', 'Excisional Biopsy'),
  ('Histopathology & Cytology', 'Fine Needle Aspiration Cytology (FNAC)'),
  ('Histopathology & Cytology', 'Flow Cytometry'),
  ('Histopathology & Cytology', 'Flow Cytometry Immunophenotyping for Leukemia/Lymphoma'),
  ('Histopathology & Cytology', 'Fluid Cytology'),
  ('Histopathology & Cytology', 'Fluorescence In Situ Hybridization (FISH)'),
  ('Histopathology & Cytology', 'FNAC of Breast Lump'),
  ('Histopathology & Cytology', 'FNAC of Lymph Node'),
  ('Histopathology & Cytology', 'FNAC of Salivary Gland'),
  ('Histopathology & Cytology', 'FNAC of Thyroid'),
  ('Histopathology & Cytology', 'Frozen Section'),
  ('Histopathology & Cytology', 'Frozen Section Biopsy'),
  ('Histopathology & Cytology', 'Gastric Biopsy'),
  ('Histopathology & Cytology', 'GATA3 Immunohistochemistry'),
  ('Histopathology & Cytology', 'GCDFP-15 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Gomori Methenamine Silver Stain (GMS)'),
  ('Histopathology & Cytology', 'HER2 Fluorescence In Situ Hybridization (HER2 FISH)'),
  ('Histopathology & Cytology', 'HER2/neu by Immunohistochemistry'),
  ('Histopathology & Cytology', 'Histopathology'),
  ('Histopathology & Cytology', 'Histopathology of Biopsy Specimen'),
  ('Histopathology & Cytology', 'Histopathology of Resection Specimen'),
  ('Histopathology & Cytology', 'HMB-45 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Immunofluorescence (IF)'),
  ('Histopathology & Cytology', 'Immunohistochemistry (IHC)'),
  ('Histopathology & Cytology', 'Imprint Cytology'),
  ('Histopathology & Cytology', 'Incisional Biopsy'),
  ('Histopathology & Cytology', 'Kappa/Lambda Light Chain In Situ Hybridization'),
  ('Histopathology & Cytology', 'Ki-67 Proliferation Index'),
  ('Histopathology & Cytology', 'Laryngeal Biopsy'),
  ('Histopathology & Cytology', 'Leukocyte Common Antigen (LCA / CD45)'),
  ('Histopathology & Cytology', 'Liquid-Based Cytology (LBC)'),
  ('Histopathology & Cytology', 'Liver Biopsy'),
  ('Histopathology & Cytology', 'Lung Biopsy'),
  ('Histopathology & Cytology', 'Lymph Node Biopsy'),
  ('Histopathology & Cytology', 'Mammaglobin Immunohistochemistry'),
  ('Histopathology & Cytology', 'Masson Trichrome Stain'),
  ('Histopathology & Cytology', 'Melan-A Immunohistochemistry'),
  ('Histopathology & Cytology', 'Minimal Residual Disease by Flow Cytometry (MRD)'),
  ('Histopathology & Cytology', 'Mismatch Repair Protein Immunohistochemistry (MMR / MLH1, MSH2, MSH6, PMS2)'),
  ('Histopathology & Cytology', 'Mucicarmine Stain'),
  ('Histopathology & Cytology', 'Muscle Biopsy'),
  ('Histopathology & Cytology', 'Nasal Biopsy'),
  ('Histopathology & Cytology', 'Nerve Biopsy'),
  ('Histopathology & Cytology', 'Neuron-Specific Enolase (NSE) Immunohistochemistry'),
  ('Histopathology & Cytology', 'Nipple Discharge Cytology'),
  ('Histopathology & Cytology', 'Oil Red O Stain'),
  ('Histopathology & Cytology', 'Omental Biopsy'),
  ('Histopathology & Cytology', 'Oral Mucosal Biopsy'),
  ('Histopathology & Cytology', 'p16 Immunohistochemistry'),
  ('Histopathology & Cytology', 'p40 Immunohistochemistry'),
  ('Histopathology & Cytology', 'p53 Immunohistochemistry'),
  ('Histopathology & Cytology', 'p63 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Papanicolaou Smear (Pap Smear)'),
  ('Histopathology & Cytology', 'PAX8 Immunohistochemistry'),
  ('Histopathology & Cytology', 'PD-L1 Immunohistochemistry'),
  ('Histopathology & Cytology', 'Periodic Acid-Schiff Stain (PAS)'),
  ('Histopathology & Cytology', 'Peritoneal Biopsy'),
  ('Histopathology & Cytology', 'Perls Prussian Blue Stain for Iron'),
  ('Histopathology & Cytology', 'Placental Histopathology'),
  ('Histopathology & Cytology', 'Pleural Biopsy'),
  ('Histopathology & Cytology', 'Pleural Fluid Cytology'),
  ('Histopathology & Cytology', 'PNH Clone by Flow Cytometry'),
  ('Histopathology & Cytology', 'Products of Conception Histopathology'),
  ('Histopathology & Cytology', 'Prostate Biopsy'),
  ('Histopathology & Cytology', 'Prostate-Specific Antigen (PSA) Immunostain'),
  ('Histopathology & Cytology', 'Punch Biopsy'),
  ('Histopathology & Cytology', 'Rectal Biopsy'),
  ('Histopathology & Cytology', 'Renal Allograft Biopsy'),
  ('Histopathology & Cytology', 'Renal Biopsy'),
  ('Histopathology & Cytology', 'Renal Immunofluorescence'),
  ('Histopathology & Cytology', 'Reticulin Stain'),
  ('Histopathology & Cytology', 'S-100 Protein Immunohistochemistry'),
  ('Histopathology & Cytology', 'Salivary Gland Biopsy'),
  ('Histopathology & Cytology', 'Shave Biopsy'),
  ('Histopathology & Cytology', 'Skin Biopsy'),
  ('Histopathology & Cytology', 'Smooth Muscle Actin (SMA)'),
  ('Histopathology & Cytology', 'Special Stains (Histochemistry)'),
  ('Histopathology & Cytology', 'Sputum Cytology'),
  ('Histopathology & Cytology', 'Synaptophysin Immunohistochemistry'),
  ('Histopathology & Cytology', 'Synovial Biopsy'),
  ('Histopathology & Cytology', 'Synovial Fluid Cytology'),
  ('Histopathology & Cytology', 'TdT Immunohistochemistry'),
  ('Histopathology & Cytology', 'Testicular Biopsy'),
  ('Histopathology & Cytology', 'Thyroid Transcription Factor-1 (TTF-1)'),
  ('Histopathology & Cytology', 'Trucut Biopsy'),
  ('Histopathology & Cytology', 'Urine Cytology'),
  ('Histopathology & Cytology', 'USG-Guided FNAC'),
  ('Histopathology & Cytology', 'Vaginal Biopsy'),
  ('Histopathology & Cytology', 'Vimentin Immunohistochemistry'),
  ('Histopathology & Cytology', 'Von Kossa Stain'),
  ('Histopathology & Cytology', 'Vulval Biopsy'),
  ('Histopathology & Cytology', 'WT1 Immunohistochemistry'),
  ('Imaging & Cardiac Investigations', '24-hour Esophageal pH Monitoring'),
  ('Imaging & Cardiac Investigations', 'Ambulatory Blood Pressure Monitoring (ABPM)'),
  ('Imaging & Cardiac Investigations', 'Anorectal Manometry'),
  ('Imaging & Cardiac Investigations', 'Barium Enema'),
  ('Imaging & Cardiac Investigations', 'Barium Meal'),
  ('Imaging & Cardiac Investigations', 'Barium Meal Follow Through'),
  ('Imaging & Cardiac Investigations', 'Barium Swallow'),
  ('Imaging & Cardiac Investigations', 'Biophysical Profile (BPP)'),
  ('Imaging & Cardiac Investigations', 'Bone Scan (Technetium)'),
  ('Imaging & Cardiac Investigations', 'Brainstem Evoked Response Audiometry (BERA)'),
  ('Imaging & Cardiac Investigations', 'Bronchoscopy'),
  ('Imaging & Cardiac Investigations', 'Capsule Endoscopy'),
  ('Imaging & Cardiac Investigations', 'Cardiac MRI'),
  ('Imaging & Cardiac Investigations', 'Carotid Doppler'),
  ('Imaging & Cardiac Investigations', 'Chest X-Ray (CXR)'),
  ('Imaging & Cardiac Investigations', 'Chest X-ray AP View'),
  ('Imaging & Cardiac Investigations', 'Chest X-ray Apical/Lordotic View'),
  ('Imaging & Cardiac Investigations', 'Chest X-ray Lateral View'),
  ('Imaging & Cardiac Investigations', 'Colonoscopy'),
  ('Imaging & Cardiac Investigations', 'Color Doppler of Lower Limb Arteries'),
  ('Imaging & Cardiac Investigations', 'Color Doppler of Lower Limb Veins'),
  ('Imaging & Cardiac Investigations', 'Color Doppler of Upper Limb'),
  ('Imaging & Cardiac Investigations', 'Colposcopy'),
  ('Imaging & Cardiac Investigations', 'Coronary Angiography (CAG)'),
  ('Imaging & Cardiac Investigations', 'Coronary Artery Calcium Score'),
  ('Imaging & Cardiac Investigations', 'CT Angiography (CT Angiogram)'),
  ('Imaging & Cardiac Investigations', 'CT Coronary Angiography'),
  ('Imaging & Cardiac Investigations', 'CT Enterography'),
  ('Imaging & Cardiac Investigations', 'CT KUB (Stone Protocol)'),
  ('Imaging & Cardiac Investigations', 'CT Pulmonary Angiography (CTPA)'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Abdomen and Pelvis'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Brain'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Chest'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Neck'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Orbit'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Paranasal Sinuses (CT PNS)'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Spine'),
  ('Imaging & Cardiac Investigations', 'CT Scan of Temporal Bone'),
  ('Imaging & Cardiac Investigations', 'CT Urogram'),
  ('Imaging & Cardiac Investigations', 'CT-Guided Biopsy / FNAC'),
  ('Imaging & Cardiac Investigations', 'Cystoscopy'),
  ('Imaging & Cardiac Investigations', 'Digital Breast Tomosynthesis (DBT)'),
  ('Imaging & Cardiac Investigations', 'Digital Subtraction Angiography (DSA)'),
  ('Imaging & Cardiac Investigations', 'Dual-Energy X-ray Absorptiometry (DEXA)'),
  ('Imaging & Cardiac Investigations', 'Echocardiography (Echo)'),
  ('Imaging & Cardiac Investigations', 'Electrocardiogram (ECG)'),
  ('Imaging & Cardiac Investigations', 'Electroencephalography (EEG)'),
  ('Imaging & Cardiac Investigations', 'Electromyography (EMG)'),
  ('Imaging & Cardiac Investigations', 'Endoscopic Retrograde Cholangiopancreatography (ERCP)'),
  ('Imaging & Cardiac Investigations', 'Endoscopic Ultrasound (EUS)'),
  ('Imaging & Cardiac Investigations', 'Esophageal Manometry'),
  ('Imaging & Cardiac Investigations', 'Exercise Tolerance Test (ETT)'),
  ('Imaging & Cardiac Investigations', 'Fetal Anomaly Scan'),
  ('Imaging & Cardiac Investigations', 'Fetal Echocardiography'),
  ('Imaging & Cardiac Investigations', 'Fluoroscopy'),
  ('Imaging & Cardiac Investigations', 'Focused Assessment with Sonography in Trauma (FAST)'),
  ('Imaging & Cardiac Investigations', 'Folliculometry'),
  ('Imaging & Cardiac Investigations', 'Fundus Fluorescein Angiography (FFA)'),
  ('Imaging & Cardiac Investigations', 'Hepatobiliary Scintigraphy (HIDA Scan)'),
  ('Imaging & Cardiac Investigations', 'Hepatoportal Doppler'),
  ('Imaging & Cardiac Investigations', 'High Resolution CT of Chest (HRCT Chest)'),
  ('Imaging & Cardiac Investigations', 'Holter Monitoring'),
  ('Imaging & Cardiac Investigations', 'Hysterosalpingography (HSG)'),
  ('Imaging & Cardiac Investigations', 'Intravenous Urogram (IVU)'),
  ('Imaging & Cardiac Investigations', 'Laryngoscopy'),
  ('Imaging & Cardiac Investigations', 'Lateral Cephalogram'),
  ('Imaging & Cardiac Investigations', 'Magnetic Resonance Angiography (MRA)'),
  ('Imaging & Cardiac Investigations', 'Magnetic Resonance Cholangiopancreatography (MRCP)'),
  ('Imaging & Cardiac Investigations', 'Magnetic Resonance Imaging (MRI)'),
  ('Imaging & Cardiac Investigations', 'Magnetic Resonance Venography (MRV)'),
  ('Imaging & Cardiac Investigations', 'Mammography (Mammogram)'),
  ('Imaging & Cardiac Investigations', 'Micturating Cystourethrogram (MCU)'),
  ('Imaging & Cardiac Investigations', 'MR Enterography'),
  ('Imaging & Cardiac Investigations', 'MRI of Abdomen'),
  ('Imaging & Cardiac Investigations', 'MRI of Brain (MRI Brain)'),
  ('Imaging & Cardiac Investigations', 'MRI of Breast'),
  ('Imaging & Cardiac Investigations', 'MRI of Cervical Spine'),
  ('Imaging & Cardiac Investigations', 'MRI of Dorsal Spine'),
  ('Imaging & Cardiac Investigations', 'MRI of Knee'),
  ('Imaging & Cardiac Investigations', 'MRI of Lumbosacral Spine'),
  ('Imaging & Cardiac Investigations', 'MRI of Neck'),
  ('Imaging & Cardiac Investigations', 'MRI of Orbit'),
  ('Imaging & Cardiac Investigations', 'MRI of Paranasal Sinuses'),
  ('Imaging & Cardiac Investigations', 'MRI of Pelvis'),
  ('Imaging & Cardiac Investigations', 'MRI of Pituitary'),
  ('Imaging & Cardiac Investigations', 'MRI of Shoulder'),
  ('Imaging & Cardiac Investigations', 'MRI of Whole Spine'),
  ('Imaging & Cardiac Investigations', 'Musculoskeletal Ultrasonography'),
  ('Imaging & Cardiac Investigations', 'Myelography'),
  ('Imaging & Cardiac Investigations', 'Myocardial Perfusion Imaging (MPI)'),
  ('Imaging & Cardiac Investigations', 'Nasal Endoscopy'),
  ('Imaging & Cardiac Investigations', 'Neonatal Cranial Ultrasonography'),
  ('Imaging & Cardiac Investigations', 'Nerve Conduction Study (NCS)'),
  ('Imaging & Cardiac Investigations', 'Nuchal Translucency Scan (NT Scan)'),
  ('Imaging & Cardiac Investigations', 'Obstetric Doppler'),
  ('Imaging & Cardiac Investigations', 'Obstetric Ultrasonography / Pregnancy Profile'),
  ('Imaging & Cardiac Investigations', 'Optical Coherence Tomography (OCT)'),
  ('Imaging & Cardiac Investigations', 'Orthopantomogram (OPG)'),
  ('Imaging & Cardiac Investigations', 'Otoacoustic Emissions (OAE)'),
  ('Imaging & Cardiac Investigations', 'Parathyroid Scintigraphy (Sestamibi Scan)'),
  ('Imaging & Cardiac Investigations', 'Peak Expiratory Flow Rate (PEFR)'),
  ('Imaging & Cardiac Investigations', 'Positron Emission Tomography-CT (PET-CT)'),
  ('Imaging & Cardiac Investigations', 'Proctoscopy'),
  ('Imaging & Cardiac Investigations', 'Pure Tone Audiometry (PTA)'),
  ('Imaging & Cardiac Investigations', 'Renal Doppler'),
  ('Imaging & Cardiac Investigations', 'Renal Scan (DTPA/DMSA)'),
  ('Imaging & Cardiac Investigations', 'Retrograde Pyelogram (RGP)'),
  ('Imaging & Cardiac Investigations', 'Retrograde Urethrogram (RGU)'),
  ('Imaging & Cardiac Investigations', 'Scanogram for Limb Length'),
  ('Imaging & Cardiac Investigations', 'Scrotal Doppler'),
  ('Imaging & Cardiac Investigations', 'Sialography'),
  ('Imaging & Cardiac Investigations', 'Sigmoidoscopy'),
  ('Imaging & Cardiac Investigations', 'Sinogram'),
  ('Imaging & Cardiac Investigations', 'Skeletal Survey'),
  ('Imaging & Cardiac Investigations', 'Somatosensory Evoked Potential (SSEP)'),
  ('Imaging & Cardiac Investigations', 'Spirometry'),
  ('Imaging & Cardiac Investigations', 'Stress Echocardiography'),
  ('Imaging & Cardiac Investigations', 'T-tube Cholangiogram'),
  ('Imaging & Cardiac Investigations', 'Thyroid Scan'),
  ('Imaging & Cardiac Investigations', 'Transcranial Doppler (TCD)'),
  ('Imaging & Cardiac Investigations', 'Transesophageal Echocardiography (TEE)'),
  ('Imaging & Cardiac Investigations', 'Transrectal Ultrasonography of Prostate (TRUS)'),
  ('Imaging & Cardiac Investigations', 'Transvaginal Ultrasonography (TVS)'),
  ('Imaging & Cardiac Investigations', 'Tympanometry'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Breast (USG Breast)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Chest / Pleural'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Hepatobiliary System (USG HBS)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Infant Hip (DDH)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of KUB (USG KUB)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Lower Abdomen (USG Lower Abdomen)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Lower Abdomen and Pelvis (USG Pelvis)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Neck / Soft Tissue'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Pregnancy Profile (USG Pregnancy Profile)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Scrotum (USG Scrotum)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Thyroid (USG Thyroid)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Upper Abdomen (USG Upper Abdomen)'),
  ('Imaging & Cardiac Investigations', 'Ultrasonography of Whole Abdomen (USG Whole Abdomen)'),
  ('Imaging & Cardiac Investigations', 'Upper GI Endoscopy'),
  ('Imaging & Cardiac Investigations', 'Urodynamic Study'),
  ('Imaging & Cardiac Investigations', 'Ventilation-Perfusion Scan (V/Q Scan)'),
  ('Imaging & Cardiac Investigations', 'Visual Evoked Potential (VEP)'),
  ('Imaging & Cardiac Investigations', 'X-Ray Abdomen Erect'),
  ('Imaging & Cardiac Investigations', 'X-ray Abdomen Supine'),
  ('Imaging & Cardiac Investigations', 'X-ray Ankle Joint'),
  ('Imaging & Cardiac Investigations', 'X-ray Both Hip Joints'),
  ('Imaging & Cardiac Investigations', 'X-ray Cervical Spine'),
  ('Imaging & Cardiac Investigations', 'X-ray Chest for Ribs'),
  ('Imaging & Cardiac Investigations', 'X-ray Coccyx'),
  ('Imaging & Cardiac Investigations', 'X-ray Dorsal Spine'),
  ('Imaging & Cardiac Investigations', 'X-ray Elbow Joint'),
  ('Imaging & Cardiac Investigations', 'X-ray Femur'),
  ('Imaging & Cardiac Investigations', 'X-ray Foot'),
  ('Imaging & Cardiac Investigations', 'X-ray Forearm'),
  ('Imaging & Cardiac Investigations', 'X-ray Hand'),
  ('Imaging & Cardiac Investigations', 'X-ray Humerus'),
  ('Imaging & Cardiac Investigations', 'X-Ray Kidney Ureter Bladder (X-Ray KUB)'),
  ('Imaging & Cardiac Investigations', 'X-ray Knee Joint'),
  ('Imaging & Cardiac Investigations', 'X-ray Leg (Tibia and Fibula)'),
  ('Imaging & Cardiac Investigations', 'X-ray Lumbosacral Spine (X-ray LS Spine)'),
  ('Imaging & Cardiac Investigations', 'X-ray Mastoid'),
  ('Imaging & Cardiac Investigations', 'X-ray Nasal Bone'),
  ('Imaging & Cardiac Investigations', 'X-ray Paranasal Sinuses (X-ray PNS)'),
  ('Imaging & Cardiac Investigations', 'X-ray Pelvis'),
  ('Imaging & Cardiac Investigations', 'X-ray Post-Nasal Space'),
  ('Imaging & Cardiac Investigations', 'X-ray Sacroiliac Joints'),
  ('Imaging & Cardiac Investigations', 'X-ray Shoulder Joint'),
  ('Imaging & Cardiac Investigations', 'X-ray Skull'),
  ('Imaging & Cardiac Investigations', 'X-ray Soft Tissue Neck'),
  ('Imaging & Cardiac Investigations', 'X-ray Temporomandibular Joint (TMJ)'),
  ('Imaging & Cardiac Investigations', 'X-ray Wrist for Bone Age'),
  ('Imaging & Cardiac Investigations', 'X-ray Wrist Joint'),
  ('Microbiology & Culture', 'Albert Stain'),
  ('Microbiology & Culture', 'Anaerobic Culture and Sensitivity'),
  ('Microbiology & Culture', 'Antimicrobial Susceptibility Testing (AST)'),
  ('Microbiology & Culture', 'Ascitic Fluid Culture and Sensitivity'),
  ('Microbiology & Culture', 'Aspirate Culture and Sensitivity'),
  ('Microbiology & Culture', 'Automated Blood Culture (BacT/ALERT / BACTEC)'),
  ('Microbiology & Culture', 'Bacterial Antigen Detection (Latex Agglutination)'),
  ('Microbiology & Culture', 'Bile Culture and Sensitivity'),
  ('Microbiology & Culture', 'Blood Culture and Sensitivity (Blood C/S)'),
  ('Microbiology & Culture', 'Blood Culture for Aerobic and Anaerobic Organisms'),
  ('Microbiology & Culture', 'Blood Film for Microfilaria'),
  ('Microbiology & Culture', 'Body Fluid Culture and Sensitivity (Fluid C/S)'),
  ('Microbiology & Culture', 'Bronchoalveolar Lavage Culture and Sensitivity (BAL C/S)'),
  ('Microbiology & Culture', 'Calcofluor White Stain'),
  ('Microbiology & Culture', 'Catheter Tip Culture and Sensitivity'),
  ('Microbiology & Culture', 'Cerebrospinal Fluid Culture and Sensitivity (CSF C/S)'),
  ('Microbiology & Culture', 'Cervical/Vaginal Swab for Trichomonas'),
  ('Microbiology & Culture', 'Corneal Scraping for Culture and Microscopy'),
  ('Microbiology & Culture', 'Dark Field Microscopy for Treponema'),
  ('Microbiology & Culture', 'Ear Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Endocervical Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Eye Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Fluorescent Auramine Stain for AFB'),
  ('Microbiology & Culture', 'Fungal Culture and Sensitivity (Fungal Culture)'),
  ('Microbiology & Culture', 'Fungal Culture from Nail, Skin and Hair'),
  ('Microbiology & Culture', 'Gastric Aspirate for AFB'),
  ('Microbiology & Culture', 'GeneXpert MTB/RIF'),
  ('Microbiology & Culture', 'GeneXpert MTB/RIF Ultra'),
  ('Microbiology & Culture', 'Giemsa Stain'),
  ('Microbiology & Culture', 'Gram Stain'),
  ('Microbiology & Culture', 'Gram Stain for Gonococci (Urethral/Cervical)'),
  ('Microbiology & Culture', 'Hanging Drop Preparation for Vibrio'),
  ('Microbiology & Culture', 'High Vaginal Swab Culture and Sensitivity (HVS C/S)'),
  ('Microbiology & Culture', 'India Ink Preparation'),
  ('Microbiology & Culture', 'Interferon Gamma Release Assay (IGRA / QuantiFERON-TB Gold)'),
  ('Microbiology & Culture', 'KOH Preparation for Fungus'),
  ('Microbiology & Culture', 'Latex Agglutination Test for Cryptococcal Antigen'),
  ('Microbiology & Culture', 'Line Probe Assay for TB (LPA)'),
  ('Microbiology & Culture', 'Malaria Rapid Diagnostic Test (Malaria RDT)'),
  ('Microbiology & Culture', 'Mantoux Test (MT)'),
  ('Microbiology & Culture', 'Minimum Inhibitory Concentration (MIC)'),
  ('Microbiology & Culture', 'Modified Acid-Fast Stain for Nocardia/Cryptosporidium'),
  ('Microbiology & Culture', 'MRSA Screening Culture'),
  ('Microbiology & Culture', 'Mycobacterium Tuberculosis Culture (TB Culture)'),
  ('Microbiology & Culture', 'Nail Culture and Sensitivity'),
  ('Microbiology & Culture', 'Nasal Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Nasopharyngeal Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Peripheral Blood Film for Malarial Parasite (MP)'),
  ('Microbiology & Culture', 'Peritoneal Dialysis Fluid Culture and Sensitivity'),
  ('Microbiology & Culture', 'Pleural Fluid Culture and Sensitivity'),
  ('Microbiology & Culture', 'Potassium Hydroxide Mount (KOH Mount)'),
  ('Microbiology & Culture', 'Prostatic Secretion Culture and Sensitivity'),
  ('Microbiology & Culture', 'Pus Culture and Sensitivity'),
  ('Microbiology & Culture', 'Semen Culture and Sensitivity (Semen C/S)'),
  ('Microbiology & Culture', 'Skin Scraping Culture'),
  ('Microbiology & Culture', 'Skin Scraping for Scabies'),
  ('Microbiology & Culture', 'Skin Smear for Leprosy (Slit Skin Smear)'),
  ('Microbiology & Culture', 'Skin Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Sputum Culture and Sensitivity (Sputum C/S)'),
  ('Microbiology & Culture', 'Sputum for Acid Fast Bacilli (Sputum for AFB)'),
  ('Microbiology & Culture', 'Sputum for AFB (Acid-Fast Bacilli)'),
  ('Microbiology & Culture', 'Sputum for Fungal Culture'),
  ('Microbiology & Culture', 'Sputum for Gram Stain and Culture'),
  ('Microbiology & Culture', 'Stool Culture and Sensitivity (Stool C/S)'),
  ('Microbiology & Culture', 'Stool for Clostridioides difficile Toxin'),
  ('Microbiology & Culture', 'Stool for Helicobacter pylori Antigen'),
  ('Microbiology & Culture', 'Stool for Occult Blood'),
  ('Microbiology & Culture', 'Stool for Reducing Substances'),
  ('Microbiology & Culture', 'Stool for Rotavirus Antigen'),
  ('Microbiology & Culture', 'Stool Routine Microscopic Examination (Stool R/E)'),
  ('Microbiology & Culture', 'Suprapubic Aspirate Culture and Sensitivity'),
  ('Microbiology & Culture', 'Synovial Fluid Culture and Sensitivity'),
  ('Microbiology & Culture', 'Throat Swab Culture and Sensitivity (Throat Swab C/S)'),
  ('Microbiology & Culture', 'Tracheal Aspirate Culture and Sensitivity'),
  ('Microbiology & Culture', 'Typhidot Test (IgM/IgG)'),
  ('Microbiology & Culture', 'Umbilical Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Urethral Swab Culture and Sensitivity'),
  ('Microbiology & Culture', 'Urine Culture and Sensitivity (Urine C/S)'),
  ('Microbiology & Culture', 'Wet Mount Microscopy'),
  ('Microbiology & Culture', 'Wound Swab Culture and Sensitivity (Wound Swab C/S)'),
  ('Microbiology & Culture', 'Ziehl-Neelsen Stain for AFB (ZN Stain)'),
  ('Molecular, PCR & Genetics', 'Adenovirus PCR'),
  ('Molecular, PCR & Genetics', 'ALK Gene Rearrangement'),
  ('Molecular, PCR & Genetics', 'Alpha-Thalassaemia Genotyping'),
  ('Molecular, PCR & Genetics', 'BCR-ABL1 Qualitative PCR'),
  ('Molecular, PCR & Genetics', 'BCR-ABL1 Quantitative PCR (International Scale)'),
  ('Molecular, PCR & Genetics', 'Beta-Thalassaemia Mutation Analysis'),
  ('Molecular, PCR & Genetics', 'BK Virus DNA PCR'),
  ('Molecular, PCR & Genetics', 'Bordetella pertussis PCR'),
  ('Molecular, PCR & Genetics', 'BRAF V600E Mutation'),
  ('Molecular, PCR & Genetics', 'BRCA1 and BRCA2 Mutation Analysis'),
  ('Molecular, PCR & Genetics', 'CALR Mutation'),
  ('Molecular, PCR & Genetics', 'Chikungunya Virus RT-PCR'),
  ('Molecular, PCR & Genetics', 'Chlamydia and Gonorrhoea Combined PCR (CT/NG)'),
  ('Molecular, PCR & Genetics', 'Chlamydia trachomatis PCR'),
  ('Molecular, PCR & Genetics', 'Chromosomal Microarray (CMA)'),
  ('Molecular, PCR & Genetics', 'COVID-19 RT-PCR (COVID RT-PCR)'),
  ('Molecular, PCR & Genetics', 'Cystic Fibrosis Mutation Analysis (CFTR)'),
  ('Molecular, PCR & Genetics', 'Cytomegalovirus and BK Virus Transplant Panel PCR'),
  ('Molecular, PCR & Genetics', 'Cytomegalovirus DNA PCR (CMV PCR)'),
  ('Molecular, PCR & Genetics', 'Dengue Virus RT-PCR'),
  ('Molecular, PCR & Genetics', 'Duchenne Muscular Dystrophy Genetic Test (DMD)'),
  ('Molecular, PCR & Genetics', 'EGFR Mutation'),
  ('Molecular, PCR & Genetics', 'Enterovirus PCR'),
  ('Molecular, PCR & Genetics', 'Epstein-Barr Virus DNA PCR (EBV PCR)'),
  ('Molecular, PCR & Genetics', 'FLT3 Mutation (ITD and TKD)'),
  ('Molecular, PCR & Genetics', 'Fragile X Analysis (FMR1)'),
  ('Molecular, PCR & Genetics', 'G6PD Gene Mutation Analysis'),
  ('Molecular, PCR & Genetics', 'Gastrointestinal Pathogen Panel PCR'),
  ('Molecular, PCR & Genetics', 'HBV DNA Quantitative (HBV DNA)'),
  ('Molecular, PCR & Genetics', 'HCV RNA Quantitative (HCV RNA)'),
  ('Molecular, PCR & Genetics', 'Helicobacter pylori PCR'),
  ('Molecular, PCR & Genetics', 'Hepatitis B Virus DNA Qualitative PCR'),
  ('Molecular, PCR & Genetics', 'Hepatitis B Virus DNA Quantitative PCR (HBV DNA)'),
  ('Molecular, PCR & Genetics', 'Hepatitis C Virus Genotyping (HCV Genotype)'),
  ('Molecular, PCR & Genetics', 'Hepatitis C Virus RNA Qualitative PCR'),
  ('Molecular, PCR & Genetics', 'Hepatitis C Virus RNA Quantitative PCR (HCV RNA)'),
  ('Molecular, PCR & Genetics', 'HER2 Gene Amplification by FISH (HER2 FISH)'),
  ('Molecular, PCR & Genetics', 'Herpes Simplex Virus 1 and 2 PCR (HSV PCR)'),
  ('Molecular, PCR & Genetics', 'HFE Gene Mutation (Hereditary Haemochromatosis)'),
  ('Molecular, PCR & Genetics', 'HIV RNA Viral Load (HIV Viral Load)'),
  ('Molecular, PCR & Genetics', 'HIV-1 Proviral DNA PCR'),
  ('Molecular, PCR & Genetics', 'HLA Typing'),
  ('Molecular, PCR & Genetics', 'HLA-B*5701 Genotyping'),
  ('Molecular, PCR & Genetics', 'HLA-B27 by PCR'),
  ('Molecular, PCR & Genetics', 'Human Herpesvirus 6 PCR (HHV-6 PCR)'),
  ('Molecular, PCR & Genetics', 'Human Papillomavirus DNA (HPV DNA)'),
  ('Molecular, PCR & Genetics', 'Human Papillomavirus Genotyping (HPV Genotype)'),
  ('Molecular, PCR & Genetics', 'IDH1 and IDH2 Mutation'),
  ('Molecular, PCR & Genetics', 'Influenza A and B RT-PCR'),
  ('Molecular, PCR & Genetics', 'JAK2 Exon 12 Mutation'),
  ('Molecular, PCR & Genetics', 'JC Virus PCR'),
  ('Molecular, PCR & Genetics', 'Karyotyping'),
  ('Molecular, PCR & Genetics', 'KRAS Mutation'),
  ('Molecular, PCR & Genetics', 'Leishmania PCR (Kala-azar PCR)'),
  ('Molecular, PCR & Genetics', 'Line Probe Assay for Drug-Resistant TB (LPA)'),
  ('Molecular, PCR & Genetics', 'Malaria PCR'),
  ('Molecular, PCR & Genetics', 'Measles Virus RT-PCR'),
  ('Molecular, PCR & Genetics', 'Meningitis and Encephalitis Panel PCR'),
  ('Molecular, PCR & Genetics', 'MGMT Promoter Methylation'),
  ('Molecular, PCR & Genetics', 'Microsatellite Instability Testing (MSI)'),
  ('Molecular, PCR & Genetics', 'MPL Mutation'),
  ('Molecular, PCR & Genetics', 'MTHFR Gene Mutation'),
  ('Molecular, PCR & Genetics', 'Mumps Virus RT-PCR'),
  ('Molecular, PCR & Genetics', 'Mycobacterium Tuberculosis PCR (MTB PCR)'),
  ('Molecular, PCR & Genetics', 'Mycoplasma genitalium PCR'),
  ('Molecular, PCR & Genetics', 'Mycoplasma pneumoniae PCR'),
  ('Molecular, PCR & Genetics', 'Neisseria gonorrhoeae PCR'),
  ('Molecular, PCR & Genetics', 'Next-Generation Sequencing Panel (NGS)'),
  ('Molecular, PCR & Genetics', 'Non-Invasive Prenatal Testing (NIPT)'),
  ('Molecular, PCR & Genetics', 'Norovirus RT-PCR'),
  ('Molecular, PCR & Genetics', 'NPM1 Mutation'),
  ('Molecular, PCR & Genetics', 'NRAS Mutation'),
  ('Molecular, PCR & Genetics', 'Parvovirus B19 DNA PCR'),
  ('Molecular, PCR & Genetics', 'PIK3CA Mutation'),
  ('Molecular, PCR & Genetics', 'PML-RARA Fusion Transcript'),
  ('Molecular, PCR & Genetics', 'QF-PCR for Aneuploidy'),
  ('Molecular, PCR & Genetics', 'Respiratory Pathogen Panel PCR'),
  ('Molecular, PCR & Genetics', 'Respiratory Syncytial Virus PCR (RSV PCR)'),
  ('Molecular, PCR & Genetics', 'ROS1 Gene Rearrangement'),
  ('Molecular, PCR & Genetics', 'Rotavirus PCR'),
  ('Molecular, PCR & Genetics', 'Salmonella typhi PCR (Enteric Fever PCR)'),
  ('Molecular, PCR & Genetics', 'Sanger Sequencing'),
  ('Molecular, PCR & Genetics', 'Spinal Muscular Atrophy Genetic Test (SMN1)'),
  ('Molecular, PCR & Genetics', 'T315I Mutation Analysis'),
  ('Molecular, PCR & Genetics', 'Toxoplasma gondii PCR'),
  ('Molecular, PCR & Genetics', 'Trichomonas vaginalis PCR'),
  ('Molecular, PCR & Genetics', 'Ureaplasma urealyticum PCR'),
  ('Molecular, PCR & Genetics', 'Varicella Zoster Virus PCR (VZV PCR)'),
  ('Molecular, PCR & Genetics', 'Whole Exome Sequencing (WES)'),
  ('Molecular, PCR & Genetics', 'Xpert MTB/RIF Ultra'),
  ('Molecular, PCR & Genetics', 'Y Chromosome Microdeletion'),
  ('Molecular, PCR & Genetics', 'Zika Virus RT-PCR'),
  ('Serology & Immunology', 'Allergen-Specific IgE Panel'),
  ('Serology & Immunology', 'Angiotensin-Converting Enzyme (ACE)'),
  ('Serology & Immunology', 'Anti-Acetylcholine Receptor Antibody (Anti-AChR)'),
  ('Serology & Immunology', 'Anti-Cardiolipin Antibody IgG/IgM (ACA)'),
  ('Serology & Immunology', 'Anti-Centromere Antibody (ACA)'),
  ('Serology & Immunology', 'Anti-Cyclic Citrullinated Peptide Antibody (Anti-CCP)'),
  ('Serology & Immunology', 'Anti-Dengue IgM Antibody (Dengue IgM)'),
  ('Serology & Immunology', 'Anti-Double Stranded DNA Antibody (Anti-dsDNA)'),
  ('Serology & Immunology', 'Anti-Endomysial Antibody (EMA)'),
  ('Serology & Immunology', 'Anti-Gastric Parietal Cell Antibody (APCA)'),
  ('Serology & Immunology', 'Anti-Gliadin Antibody (AGA)'),
  ('Serology & Immunology', 'Anti-Glomerular Basement Membrane Antibody (Anti-GBM)'),
  ('Serology & Immunology', 'Anti-Glutamic Acid Decarboxylase Antibody (Anti-GAD)'),
  ('Serology & Immunology', 'Anti-Hepatitis A Virus Antibody (Anti-HAV)'),
  ('Serology & Immunology', 'Anti-Hepatitis B Core Antibody (Anti-HBc)'),
  ('Serology & Immunology', 'Anti-Hepatitis B Surface Antibody (Anti-HBs)'),
  ('Serology & Immunology', 'Anti-Hepatitis C Virus Antibody (Anti-HCV)'),
  ('Serology & Immunology', 'Anti-Hepatitis E Virus Antibody (Anti-HEV)'),
  ('Serology & Immunology', 'Anti-Histone Antibody'),
  ('Serology & Immunology', 'Anti-Intrinsic Factor Antibody'),
  ('Serology & Immunology', 'Anti-Jo-1 Antibody'),
  ('Serology & Immunology', 'Anti-La/SSB Antibody'),
  ('Serology & Immunology', 'Anti-Liver Kidney Microsomal Antibody (Anti-LKM)'),
  ('Serology & Immunology', 'Anti-Mitochondrial Antibody (AMA)'),
  ('Serology & Immunology', 'Anti-Myeloperoxidase Antibody (MPO-ANCA)'),
  ('Serology & Immunology', 'Anti-Nuclear Antibody Profile (ANA Profile)'),
  ('Serology & Immunology', 'Anti-Proteinase 3 Antibody (PR3-ANCA)'),
  ('Serology & Immunology', 'Anti-RNP Antibody (Anti-U1RNP)'),
  ('Serology & Immunology', 'Anti-Ro/SSA Antibody'),
  ('Serology & Immunology', 'Anti-Saccharomyces cerevisiae Antibody (ASCA)'),
  ('Serology & Immunology', 'Anti-Scl-70 Antibody (Anti-Topoisomerase I)'),
  ('Serology & Immunology', 'Anti-Smith Antibody (Anti-Sm)'),
  ('Serology & Immunology', 'Anti-Smooth Muscle Antibody (ASMA)'),
  ('Serology & Immunology', 'Anti-Streptolysin O Titre (ASO)'),
  ('Serology & Immunology', 'Anti-Tissue Transglutaminase Antibody (Anti-tTG)'),
  ('Serology & Immunology', 'Anti-Tissue Transglutaminase Antibody IgA (tTG-IgA)'),
  ('Serology & Immunology', 'Antineutrophil Cytoplasmic Antibody (ANCA)'),
  ('Serology & Immunology', 'Antinuclear Antibody (ANA)'),
  ('Serology & Immunology', 'Aspergillus Galactomannan Antigen'),
  ('Serology & Immunology', 'Brucella Agglutination Test'),
  ('Serology & Immunology', 'C1 Esterase Inhibitor'),
  ('Serology & Immunology', 'Cancer Antigen 72-4 (CA 72-4)'),
  ('Serology & Immunology', 'CD4 T-Cell Count'),
  ('Serology & Immunology', 'Chikungunya Antibody IgG'),
  ('Serology & Immunology', 'Chikungunya Antibody IgM'),
  ('Serology & Immunology', 'CMV DNA PCR'),
  ('Serology & Immunology', 'Cold Agglutinins'),
  ('Serology & Immunology', 'Cryoglobulin'),
  ('Serology & Immunology', 'Cytomegalovirus Antibody IgG (CMV IgG)'),
  ('Serology & Immunology', 'Cytomegalovirus Antibody IgM (CMV IgM)'),
  ('Serology & Immunology', 'Cytomegalovirus IgG and IgM (CMV IgG/IgM)'),
  ('Serology & Immunology', 'Dengue Antibody IgG'),
  ('Serology & Immunology', 'Dengue Antibody IgM'),
  ('Serology & Immunology', 'Dengue IgG and IgM Antibody (Dengue IgG/IgM)'),
  ('Serology & Immunology', 'Dengue NS1 Antigen'),
  ('Serology & Immunology', 'Epstein-Barr Virus EBNA Antibody (EBNA)'),
  ('Serology & Immunology', 'Epstein-Barr Virus VCA IgG (EBV VCA IgG)'),
  ('Serology & Immunology', 'Epstein-Barr Virus VCA IgM (EBV VCA IgM)'),
  ('Serology & Immunology', 'Extractable Nuclear Antigen Panel (ENA Panel)'),
  ('Serology & Immunology', 'Filaria Antigen Test'),
  ('Serology & Immunology', 'Fluorescent Treponemal Antibody Absorption Test (FTA-ABS)'),
  ('Serology & Immunology', 'Helicobacter Pylori Antibody (H. pylori IgG)'),
  ('Serology & Immunology', 'Helicobacter pylori Antibody IgG (H. pylori IgG)'),
  ('Serology & Immunology', 'Helicobacter pylori Stool Antigen'),
  ('Serology & Immunology', 'Hepatitis A Virus Antibody IgM (Anti-HAV IgM)'),
  ('Serology & Immunology', 'Hepatitis A Virus Antibody Total/IgG (Anti-HAV)'),
  ('Serology & Immunology', 'Hepatitis B Core Antibody IgM (Anti-HBc IgM)'),
  ('Serology & Immunology', 'Hepatitis B Core Antibody Total (Anti-HBc Total)'),
  ('Serology & Immunology', 'Hepatitis B e Antibody (Anti-HBe)'),
  ('Serology & Immunology', 'Hepatitis B e Antigen (HBeAg)'),
  ('Serology & Immunology', 'Hepatitis B Surface Antibody (Anti-HBs)'),
  ('Serology & Immunology', 'Hepatitis B Surface Antigen (HBsAg)'),
  ('Serology & Immunology', 'Hepatitis B Virus DNA PCR (HBV DNA)'),
  ('Serology & Immunology', 'Hepatitis C Virus Antibody (Anti-HCV)'),
  ('Serology & Immunology', 'Hepatitis C Virus RNA PCR (HCV RNA)'),
  ('Serology & Immunology', 'Hepatitis D Virus Antibody (Anti-HDV)'),
  ('Serology & Immunology', 'Hepatitis E Virus Antibody IgG (Anti-HEV IgG)'),
  ('Serology & Immunology', 'Hepatitis E Virus Antibody IgM (Anti-HEV IgM)'),
  ('Serology & Immunology', 'Herpes Simplex Virus 1 & 2 Antibody IgG (HSV IgG)'),
  ('Serology & Immunology', 'Herpes Simplex Virus 1 & 2 Antibody IgM (HSV IgM)'),
  ('Serology & Immunology', 'Herpes Simplex Virus IgG and IgM (HSV IgG/IgM)'),
  ('Serology & Immunology', 'HIV 1 & 2 Antibody/Antigen Combo (HIV Ag/Ab)'),
  ('Serology & Immunology', 'HIV 1 and 2 Antibody'),
  ('Serology & Immunology', 'HIV p24 Antigen'),
  ('Serology & Immunology', 'HIV Western Blot'),
  ('Serology & Immunology', 'HIV-1 RNA Viral Load'),
  ('Serology & Immunology', 'HLA-B27'),
  ('Serology & Immunology', 'IgG Subclasses (IgG1-4)'),
  ('Serology & Immunology', 'Immunofixation Electrophoresis (IFE)'),
  ('Serology & Immunology', 'Immunoglobulin A (IgA)'),
  ('Serology & Immunology', 'Immunoglobulin G (IgG)'),
  ('Serology & Immunology', 'Immunoglobulin M (IgM)'),
  ('Serology & Immunology', 'Japanese Encephalitis Antibody IgM (JE IgM)'),
  ('Serology & Immunology', 'Kala-azar rK39 Rapid Test'),
  ('Serology & Immunology', 'Leptospira Antibody IgM (Lepto IgM)'),
  ('Serology & Immunology', 'Malaria Parasite (MP)'),
  ('Serology & Immunology', 'Measles Antibody IgM/IgG'),
  ('Serology & Immunology', 'Monospot Test (Heterophile Antibody)'),
  ('Serology & Immunology', 'Mumps Antibody IgM/IgG'),
  ('Serology & Immunology', 'Neuron-Specific Enolase (NSE)'),
  ('Serology & Immunology', 'Prostate-Specific Antigen Total (PSA)'),
  ('Serology & Immunology', 'QuantiFERON-TB Gold (IGRA)'),
  ('Serology & Immunology', 'Rapid Plasma Reagin (RPR)'),
  ('Serology & Immunology', 'Rapid Test for Malaria (Malaria RDT)'),
  ('Serology & Immunology', 'Rheumatoid Factor (RA Factor)'),
  ('Serology & Immunology', 'Rubella Antibody IgG'),
  ('Serology & Immunology', 'Rubella Antibody IgM'),
  ('Serology & Immunology', 'Rubella IgG and IgM (Rubella IgG/IgM)'),
  ('Serology & Immunology', 'SARS-CoV-2 Antibody (COVID-19 Antibody)'),
  ('Serology & Immunology', 'Scrub Typhus Antibody IgM'),
  ('Serology & Immunology', 'Serum Complement C3'),
  ('Serology & Immunology', 'Serum Complement C4'),
  ('Serology & Immunology', 'Serum Cryptococcal Antigen (CrAg)'),
  ('Serology & Immunology', 'Serum Free Light Chains (Kappa/Lambda)'),
  ('Serology & Immunology', 'Serum Immunoglobulin A (IgA)'),
  ('Serology & Immunology', 'Serum Immunoglobulin E (IgE)'),
  ('Serology & Immunology', 'Serum Immunoglobulin G (IgG)'),
  ('Serology & Immunology', 'Serum Immunoglobulin M (IgM)'),
  ('Serology & Immunology', 'Serum Procalcitonin (PCT)'),
  ('Serology & Immunology', 'Serum Protein Electrophoresis (SPEP)'),
  ('Serology & Immunology', 'Serum Widal Test'),
  ('Serology & Immunology', 'TORCH Panel'),
  ('Serology & Immunology', 'Total Hemolytic Complement (CH50)'),
  ('Serology & Immunology', 'Total Immunoglobulin E (Total IgE)'),
  ('Serology & Immunology', 'Total Serum IgE Allergy Screen (Phadiatop)'),
  ('Serology & Immunology', 'Toxoplasma Antibody IgG (Toxo IgG)'),
  ('Serology & Immunology', 'Toxoplasma Antibody IgM (Toxo IgM)'),
  ('Serology & Immunology', 'Toxoplasma IgG and IgM (Toxo IgG/IgM)'),
  ('Serology & Immunology', 'Treponema Pallidum Hemagglutination Assay (TPHA)'),
  ('Serology & Immunology', 'Typhidot IgM/IgG'),
  ('Serology & Immunology', 'Typhoid IgM'),
  ('Serology & Immunology', 'Varicella Zoster Virus Antibody IgM/IgG (VZV)'),
  ('Serology & Immunology', 'Venereal Disease Research Laboratory Test (VDRL)'),
  ('Serology & Immunology', 'Weil-Felix Test'),
  ('Serology & Immunology', 'Zika Virus Antibody'),
  ('Tumour Markers, Vitamins & Specialised', 'Alpha Fetoprotein (AFP)'),
  ('Tumour Markers, Vitamins & Specialised', 'Alpha-1 Antitrypsin (A1AT)'),
  ('Tumour Markers, Vitamins & Specialised', 'Alpha-Fetoprotein L3 Fraction (AFP-L3)'),
  ('Tumour Markers, Vitamins & Specialised', 'Beta Human Chorionic Gonadotropin, Tumour Marker (Beta-hCG)'),
  ('Tumour Markers, Vitamins & Specialised', 'Beta-2 Microglobulin (B2M)'),
  ('Tumour Markers, Vitamins & Specialised', 'Blood Lead Level'),
  ('Tumour Markers, Vitamins & Specialised', 'Cancer Antigen 125 (CA 125)'),
  ('Tumour Markers, Vitamins & Specialised', 'Cancer Antigen 15-3 (CA 15-3)'),
  ('Tumour Markers, Vitamins & Specialised', 'Cancer Antigen 19-9 (CA 19-9)'),
  ('Tumour Markers, Vitamins & Specialised', 'Cancer Antigen 27.29 (CA 27-29)'),
  ('Tumour Markers, Vitamins & Specialised', 'Carcinoembryonic Antigen (CEA)'),
  ('Tumour Markers, Vitamins & Specialised', 'Cytokeratin 19 Fragment (CYFRA 21-1)'),
  ('Tumour Markers, Vitamins & Specialised', 'Des-Gamma-Carboxy Prothrombin (PIVKA-II)'),
  ('Tumour Markers, Vitamins & Specialised', 'Free Prostate Specific Antigen (Free PSA)'),
  ('Tumour Markers, Vitamins & Specialised', 'Free to Total PSA Ratio (PSA Ratio)'),
  ('Tumour Markers, Vitamins & Specialised', 'Human Epididymis Protein 4 (HE4)'),
  ('Tumour Markers, Vitamins & Specialised', 'Methylmalonic Acid (MMA)'),
  ('Tumour Markers, Vitamins & Specialised', 'Placental Alkaline Phosphatase (PLAP)'),
  ('Tumour Markers, Vitamins & Specialised', 'Pro-Gastrin-Releasing Peptide (ProGRP)'),
  ('Tumour Markers, Vitamins & Specialised', 'Prostate Specific Antigen (PSA)'),
  ('Tumour Markers, Vitamins & Specialised', 'Prostatic Acid Phosphatase (PAP)'),
  ('Tumour Markers, Vitamins & Specialised', 'Risk of Ovarian Malignancy Algorithm (ROMA)'),
  ('Tumour Markers, Vitamins & Specialised', 'S-100 Protein (S-100)'),
  ('Tumour Markers, Vitamins & Specialised', 'Serum Erythropoietin (EPO)'),
  ('Tumour Markers, Vitamins & Specialised', 'Serum Folate'),
  ('Tumour Markers, Vitamins & Specialised', 'Serum Tryptase'),
  ('Tumour Markers, Vitamins & Specialised', 'Serum Vitamin B12 (Vitamin B12)'),
  ('Tumour Markers, Vitamins & Specialised', 'Squamous Cell Carcinoma Antigen (SCC)'),
  ('Tumour Markers, Vitamins & Specialised', 'Tissue Polypeptide Antigen (TPA)'),
  ('Tumour Markers, Vitamins & Specialised', 'Urinary 5-Hydroxyindoleacetic Acid (5-HIAA)'),
  ('Tumour Markers, Vitamins & Specialised', 'Urinary Catecholamines'),
  ('Tumour Markers, Vitamins & Specialised', 'Urinary Metanephrines'),
  ('Tumour Markers, Vitamins & Specialised', 'Urinary Vanillylmandelic Acid (VMA)'),
  ('Tumour Markers, Vitamins & Specialised', 'Urine Protein Electrophoresis (UPEP)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin A (Retinol)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin B1 (Thiamine)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin B12 (Cobalamin)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin B2 (Riboflavin)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin B6 (Pyridoxine)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin C (Ascorbic Acid)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin D, 1,25-Dihydroxy (Calcitriol)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin D, 25-Hydroxy (25-OH Vitamin D)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin E (Alpha-Tocopherol)'),
  ('Tumour Markers, Vitamins & Specialised', 'Vitamin K');
