-- 0095_advice.sql
-- The list of advice lines a doctor picks from on the prescription pad.
--
-- The pad's General Advice section was a free-text box, the same line typed
-- out by hand on every visit. Now it searches this list as they type, like
-- Investigation (0094), and a line that isn't on it can still be typed in.
--
-- 271 standard advice lines in 16 care areas, from the standard library a
-- Bangladeshi prescription tool ships (prescriply.bd's Library, Advice tab,
-- read on 2026-09-16). `sort_order` keeps that library's order: the care
-- areas in turn, and the lines within each as it lists them.
--
-- A global lookup like investigations: the same for every hospital.
-- Signed-in users read it and only the super admin writes.

create table public.advice (
  id         uuid primary key default gen_random_uuid(),
  text       text not null
               constraint advice_text_check check (length(btrim(text)) between 1 and 500),
  -- "Diet & nutrition", "Follow-up & warning signs", ...
  category   text,
  -- Lower first. Ties fall back to the text.
  sort_order integer not null default 0,
  -- Hidden from the pad's picker; prescriptions that already carry it keep it.
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index advice_text_key on public.advice (lower(btrim(text)));
create index advice_category_idx on public.advice (category);

create trigger advice_set_updated_at
  before update on public.advice
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- RLS ---

alter table public.advice enable row level security;

create policy advice_select on public.advice
  for select to authenticated
  using (true);

create policy advice_write on public.advice
  for all to authenticated
  using (public.is_super_admin())
  with check (public.is_super_admin());

-- No personal data in here, so the audit trail keeps whole rows.
select public.attach_audit('public.advice', true);

comment on table public.advice is
  'Advice lines a doctor picks from on the prescription pad (0095). A global lookup; the super admin edits it.';

-- ------------------------------------------------------------------ data ---

insert into public.advice (category, text, sort_order)
select c->>'category', btrim(t), (ci * 100 + ti)::int
from jsonb_array_elements($json$[
{"category":"General care & recovery","lines":["Take your medicines exactly as the doctor has prescribed.","Do not stop your medicine early even if you start feeling better.","Complete the full course of medicine as prescribed.","Take your medicine at the same time each day so you do not forget.","Do not take any extra medicine on your own without asking the doctor.","Keep this prescription safe and bring it on your next visit.","Get enough rest and sleep to help your body recover.","Wash your hands well with soap before eating and after using the toilet.","Store your medicines in a cool, dry place away from direct sunlight.","Keep all medicines out of the reach of children.","Do not use any medicine after its expiry date.","Do not share your medicines with family members or others.","Return for your follow-up visit on the date advised by the doctor.","Tell the doctor about any other medicines you are already taking.","Return sooner if your symptoms get worse or do not improve.","Keep the affected area clean and avoid heavy activity until you recover.","Follow the doctor's advice on food and daily activity during recovery."]},
{"category":"Diet & nutrition","lines":["Eat a balanced diet with rice, lentils, fish, eggs, and plenty of vegetables every day.","Eat a variety of colourful fruits and vegetables every day.","Drink plenty of safe, clean water throughout the day.","Wash fruits and vegetables well before eating them.","Always eat freshly cooked, well-covered, and properly heated food.","Avoid oily, fried, and heavy foods while you are unwell.","Avoid street food and uncovered food, especially when you are sick.","Wash your hands with soap before eating and before preparing food.","Eat small, frequent meals instead of one or two large meals.","Take less salt in your food and avoid extra salt at the table.","Cut down on sugary drinks, sweets, and desserts.","Choose home-cooked meals over packaged and processed foods.","Eat your meals slowly and chew your food well.","Do not skip breakfast; start your day with a proper meal.","Include fibre-rich foods like vegetables, fruits, and whole grains to help digestion.","Avoid eating a heavy meal just before going to bed.","When you have loose motions, take extra fluids and light, easily digestible food."]},
{"category":"Fluids & hydration","lines":["Drink plenty of safe water throughout the day.","Always drink boiled or purified water.","Drink extra fluids when you have a fever.","Drink a glass of oral saline after each loose motion.","Prepare oral saline with clean water and use it within a few hours.","Sip fluids slowly and often instead of drinking a large amount at once.","Increase your fluids in hot weather to avoid dehydration.","Watch for signs of dehydration such as dry mouth, dizziness, or passing little urine.","Choose water, fresh fruit juice, coconut water, or clear soup for extra fluids.","Limit tea, coffee, and other caffeinated drinks.","Avoid soft drinks and sugary bottled drinks.","Do not drink alcohol while you are unwell or dehydrated.","Keep drinking fluids even if you do not feel thirsty.","Encourage a sick child to keep taking small, frequent sips of fluid.","Store drinking water in a clean, covered container.","Wash your hands before preparing or drinking water and food.","Return promptly if you cannot keep any fluids down."]},
{"category":"Fever, pain & symptom care","lines":["Take plenty of rest until you feel fully better.","Drink extra water and fluids to stay hydrated during fever.","Wear light, loose clothing and do not cover yourself with heavy blankets during fever.","For a high fever, sponge your body with lukewarm water.","Do not use ice-cold water for sponging, as it can cause shivering.","Check and note your temperature two or three times a day.","Keep the room airy and comfortably cool.","Eat light, easily digestible food even if your appetite is low.","Avoid heavy work and strenuous activity while you have fever or pain.","Take your medicine exactly as prescribed and do not add extra fever or pain medicine on your own.","Return if the fever lasts more than three days or keeps rising.","Seek care urgently if you have difficulty breathing, chest pain, or confusion.","Seek care urgently for severe headache, neck stiffness, or a spreading rash.","Report at once if you notice bleeding from the gums or nose or spots under the skin.","Watch for warning signs like severe abdominal pain, repeated vomiting, or restlessness, and come back if they appear.","For a child with fever, keep them lightly dressed and offer frequent small sips of fluid.","Do not take pain medicine on an empty stomach unless advised.","Return if the pain becomes severe or does not improve as expected."]},
{"category":"Taking medicines safely","lines":["Take your medicines exactly as your doctor has prescribed.","Finish the full course of medicine even if you feel better.","Take each medicine at the same time every day so you do not forget.","Take your medicine before or after food as advised on the prescription.","Swallow tablets and capsules with a full glass of clean water.","Do not take more than the prescribed amount to feel better faster.","If you miss a dose, take it as soon as you remember, but do not double the next dose.","Never share your medicines with family members or friends.","Do not take medicine left over from a previous illness without asking your doctor.","Keep all medicines out of the reach and sight of children.","Check the expiry date before taking any medicine and discard expired ones safely.","Tell your doctor about all other medicines and supplements you are already taking.","Tell your doctor if you are pregnant, breastfeeding, or planning to have a baby.","Stop the medicine and contact your doctor if you notice a rash, swelling, or difficulty breathing.","Report any new or troubling side-effect to your doctor promptly.","Do not buy prescription medicines from the pharmacy without a valid prescription.","Bring your prescription and medicine list to every follow-up visit."]},
{"category":"Diabetes self-care","lines":["Check your blood sugar regularly as advised and keep a record to show at each visit.","Eat meals at regular times every day and do not skip any meal.","Fill half your plate with vegetables and choose smaller portions of rice.","Cut down on sweets, sugary drinks, and desserts.","Drink plenty of plain water through the day.","Walk briskly for about 30 minutes on most days of the week.","Check your feet every day for cuts, blisters, or sores.","Wash and dry your feet daily and keep the skin between your toes dry.","Wear soft, well-fitting closed shoes and avoid walking barefoot.","Do not cut corns or calluses yourself; show them to your doctor.","Keep taking your medicines as prescribed even when you feel well.","Always carry a few sweets or glucose in case your sugar drops.","If you feel shaky, sweaty, dizzy, or very hungry, eat something sweet right away.","Avoid tobacco in all forms and limit fried and oily foods.","Come for regular follow-up visits and get your eyes and kidneys checked as advised.","Tell your doctor if you notice increased thirst, frequent urination, or unusual tiredness.","Care for any wound promptly and seek help early if it does not heal.","Get enough sleep and try to manage daily stress."]},
{"category":"Blood pressure & heart health","lines":["Take your blood pressure medicines every day, even when you feel completely well.","Do not skip or stop any medicine on your own; talk to your doctor first.","Check your blood pressure regularly and keep a simple record of the readings.","Eat less salt and avoid extra table salt, pickles, and salty snacks.","Avoid fried, oily, and fatty foods, and eat more vegetables and fruits.","Walk briskly for about half an hour on most days of the week.","Do not smoke and stay away from tobacco, zarda, and gul in any form.","Avoid betel nut (supari) and limit tea and coffee.","Try to keep a healthy body weight and reduce your belly fat.","Manage stress with rest, prayer, or relaxation, and get enough sleep at night.","Take rest and sit down if you feel dizzy, and stand up slowly.","Seek help immediately if you have chest pain, breathing difficulty, or weakness on one side of the body.","Return sooner if you get severe headache, blurred vision, or a very high reading.","Attend all follow-up visits so your treatment can be reviewed and adjusted.","Bring your medicine list and blood pressure records to every visit.","Limit alcohol completely and avoid over-the-counter painkillers without advice."]},
{"category":"Cough, cold & respiratory","lines":["Drink plenty of warm fluids like water, soup, and warm tea throughout the day.","Take steam inhalation two to three times a day to ease a blocked nose and chest.","Cover your mouth and nose with a tissue or your elbow when you cough or sneeze.","Wash your hands often with soap and water, especially before eating.","Wear a mask when you go out or when you are around other people.","Stay away from smoke, dust, and strong fumes that can irritate your throat and lungs.","Do not smoke and stay away from other people who are smoking.","Gargle with warm salt water a few times a day to soothe a sore throat.","Keep yourself warm and avoid sudden cold air or cold water.","Eat light, warm, and easily digestible meals while you are unwell.","Keep your room airy and clean to help you breathe more comfortably.","Avoid close contact with others and stay home when you have fever or a bad cough.","Seek urgent medical care if you have difficulty breathing or shortness of breath.","Return to the doctor if your cough or cold does not improve within a week.","Get urgent help if your lips or fingertips turn bluish, or you feel chest tightness.","Seek care right away if you cough up blood or have a very high fever.","Drink warm honey with lukewarm water to soothe your throat, if you are not a young infant."]},
{"category":"Digestive health","lines":["Avoid spicy, oily, and fried foods until you feel better.","Eat your meals at fixed times every day.","Eat smaller meals more often instead of a few large ones.","Do not lie down for at least two hours after eating.","Chew your food slowly and eat calmly.","Boil or purify drinking water if you are unsure it is safe.","Wash your hands with soap before eating and after using the toilet.","Avoid roadside or stale food to prevent stomach infections.","Eat more fruits, vegetables, and high-fibre foods for constipation.","During loose motion, drink oral saline to stay hydrated.","Limit tea, coffee, and carbonated drinks if they upset your stomach.","Avoid smoking and alcohol, as they can worsen stomach problems.","Take a short walk after meals to help digestion.","Return if vomiting, severe stomach pain, or blood in stool occurs.","Return if loose motion continues for more than three days."]},
{"category":"Pregnancy & antenatal care","lines":["Attend all your scheduled antenatal check-ups, even if you feel well.","Eat a balanced diet with rice, lentils, fish or egg, vegetables, and fruit every day.","Take the iron and folate supplements exactly as prescribed by your doctor.","Get enough rest and try to sleep on your side for comfort.","Avoid lifting heavy loads and doing strenuous physical work.","Wash your hands well and eat freshly cooked, hygienic food to prevent infection.","Do not take any medicine without asking your doctor first.","Stay away from smoking, tobacco, betel nut, and alcohol during pregnancy.","Take short daily walks and do gentle activity as advised by your doctor.","Keep all your check-up reports and ultrasound papers together for every visit.","Plan for delivery at a hospital or clinic with trained birth attendants.","Keep emergency phone numbers and transport arranged before your due date.","Go to hospital immediately if you have heavy bleeding from the vagina.","Seek care at once if you have severe headache, blurred vision, or swelling of the face and hands.","Contact your doctor right away if you feel the baby moving much less than usual.","Go to hospital urgently if you have high fever, severe abdominal pain, or fluid leaking from the vagina.","Ask your doctor about the recommended vaccines during pregnancy."]},
{"category":"Child & newborn care","lines":["Feed your baby only breast milk for the first six months, with nothing else, not even water.","Breastfeed your baby often, both day and night, whenever the baby wants.","After six months, start soft home-made family foods along with continued breastfeeding.","Give all vaccines on time according to the national immunisation schedule.","Bring your baby's vaccination card to every visit.","Keep your newborn warm and cover the head, especially in cold weather.","Wash your hands with soap before feeding or handling the baby.","Keep the cord stump clean and dry, and do not apply anything on it.","If your baby has loose motions, keep giving oral saline and continue breastfeeding.","Do not stop feeding during diarrhoea; give extra fluids instead.","Use only clean, boiled and cooled water for the baby.","Come back right away if the baby feeds poorly, is very drowsy, or is hard to wake.","Seek care immediately if the baby has fast or difficult breathing.","Return quickly if the baby has fever, feels cold to touch, or has convulsions.","Bring the baby back for regular weight and growth check-ups.","Keep the baby away from smoke, dust, and people who are unwell.","Put the baby to sleep on the back in a safe, clear space.","Seek care if the baby passes very little urine or shows signs of dehydration."]},
{"category":"Skin & wound care","lines":["Keep the affected skin or wound clean and dry.","Wash your hands before and after touching the wound or dressing.","Do not scratch, pick, or rub the affected area.","Keep the wound covered with a clean dressing as advised.","Change the dressing when it becomes wet or dirty.","Gently clean the area with clean water and pat it dry.","Avoid harsh soaps, perfumes, and strong chemicals on the affected skin.","Watch for increasing redness, swelling, warmth, pus, or bad smell and return if these appear.","Return promptly if you develop fever along with a worsening wound.","Do not apply any household or unprescribed substance to the wound.","Protect the affected skin from direct sunlight and wear covering clothing.","Wear loose, clean cotton clothing over the affected area.","Avoid soaking the wound in pond, river, or standing water.","Trim your fingernails short and keep them clean to reduce infection risk.","Drink plenty of water and eat a balanced diet to help healing.","Keep the affected part raised when resting if it is swollen.","Do not share towels, razors, or personal items until healed.","Complete the full course of medicine as prescribed and attend follow-up as advised."]},
{"category":"Post-operative / post-procedure care","lines":["Keep the operated area and dressing clean and dry at all times.","Do not remove or change the dressing yourself unless told to.","Wash your hands before and after touching near the wound.","Do not scratch, rub, or press on the wound.","Rest well and avoid heavy work or lifting until allowed.","Avoid strenuous exercise and return to activity gradually.","Take your medicines exactly as prescribed and finish the full course.","Eat healthy food and drink plenty of safe water to help healing.","Attend your follow-up visit and suture removal on the given date.","Return sooner if the wound bleeds, swells, or becomes more painful.","Return promptly if you develop fever after the procedure.","Report any pus, foul smell, or redness spreading around the wound.","Keep the operated part raised when resting if advised, to reduce swelling.","Avoid smoking and alcohol, as they slow down wound healing.","Do not apply any home remedy, oil, or powder on the wound.","Wear loose, clean clothing over the operated area.","Ask before resuming driving, bathing, or returning to work.","Go to the nearest hospital urgently if you feel very unwell or faint."]},
{"category":"Eye, ENT & dental","lines":["Wash your hands before touching your eyes, ears, or mouth.","Do not rub your eyes, even when they feel itchy.","Do not use eye drops on your own without a doctor's advice.","Rinse your eyes gently with clean water if dust gets in.","Give your eyes regular breaks when using a phone or computer for long periods.","Wear protective glasses when working with dust, chemicals, or bright sunlight.","Do not put sharp objects, pins, or cotton buds inside your ears.","Keep your ears dry after bathing or swimming.","Do not pour oil or unprescribed drops into your ears.","Brush your teeth twice a day, in the morning and before bed.","Rinse your mouth with clean water after every meal.","Gargle with warm salt water to soothe a sore throat.","Limit sweets and sugary drinks to protect your teeth.","Avoid chewing tobacco, betel nut, and similar products.","See a dentist regularly for a check-up and cleaning.","Do not share towels, handkerchiefs, or eye cosmetics with others.","Return if you notice eye redness, ear pain, or bleeding gums that do not improve."]},
{"category":"Lifestyle & prevention","lines":["Stop using tobacco and smoking in every form.","Avoid chewing betel nut, zarda, and gul.","Stay away from second-hand smoke at home and work.","Walk briskly for at least half an hour on most days.","Stay physically active and avoid sitting for long hours.","Get seven to eight hours of sleep every night.","Take time to relax and manage daily stress.","Drink only safe, clean, or boiled water.","Eat plenty of fresh vegetables and fruits every day.","Cut down on extra salt, oil, sugar, and fried foods.","Keep your weight in a healthy range.","Cover your mouth and nose when you cough or sneeze.","Limit or avoid alcohol.","Keep your surroundings clean and free of mosquito breeding water.","Go for regular health check-ups even when you feel well."]},
{"category":"Follow-up & warning signs","lines":["Attend your follow-up visit on the date advised, even if you feel better.","Complete all the tests and investigations that were advised.","Bring all your reports and previous prescriptions to your next visit.","Seek urgent care immediately if you have severe difficulty breathing.","Seek urgent care immediately if you have chest pain or a tight feeling in the chest.","Go to the nearest hospital if you cannot keep any food or water down due to constant vomiting.","Seek urgent care if you notice you are passing very little or no urine.","Seek emergency care right away if you feel confused, very drowsy, or difficult to wake.","Return promptly if fever lasts more than three days or keeps rising.","Seek urgent care if you faint, feel severely dizzy, or are unable to stand.","Go to hospital immediately if you notice bleeding that does not stop.","Seek urgent care for a sudden severe headache or a stiff, painful neck.","Watch for any new or worsening symptom and report it without delay.","Keep a simple note of your symptoms to share at your follow-up visit.","Do not stop your treatment on your own without discussing it with the doctor first.","Save an emergency contact number so you can reach help quickly if needed."]}
]$json$::jsonb) with ordinality as cat(c, ci),
     jsonb_array_elements_text(c->'lines') with ordinality as line(t, ti);
