-- 0096_bd_locations.sql
-- Bangladesh's divisions, districts and upazilas, as tables that point at
-- each other: division >> district >> upazila.
--
-- Hospitals and chambers kept their division, district and subdistrict as
-- free text, and the site's pickers used a short list in src/data that only
-- knew a dozen districts' upazilas. Now the whole country is here, and the
-- Find Doctors filters read it.
--
-- The data: 8 divisions, 64 districts and 494 upazilas from
-- nuhil/bangladesh-geocode (read 2026-09-16), which carries the new ones
-- (Lalmai, Eidgaon, Dasar, Madhyanagar). Names are in the current official
-- spelling — Cumilla, Barishal, Bogura, Jashore, Cox's Bazar — and every
-- older or common spelling (Comilla, Barisal, Bogra, Jessore, Coxsbazar...)
-- is kept in `aliases`, so a search or a hospital's typed district finds it
-- either way. Bangla names are in `bn_name`.
--
-- Dhaka District's five upazilas (Savar, Dhamrai, Keraniganj, Nawabganj,
-- Dohar) leave out the city itself, so the 50 Dhaka Metropolitan Police
-- thanas (Gulshan, Dhanmondi, Mirpur...) sit beside them with kind 'thana'.
--
-- The three tables are global lookups: anyone may read them — the public
-- doctor and hospital search runs signed out — and only the super admin
-- writes.

create table public.bd_divisions (
  id         smallint generated by default as identity primary key,
  name       text not null
               constraint bd_divisions_name_check check (length(btrim(name)) between 1 and 100),
  bn_name    text,
  -- Other spellings: "Chittagong", "Barisal".
  aliases    text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.bd_districts (
  id          smallint generated by default as identity primary key,
  division_id smallint not null references public.bd_divisions (id) on delete restrict,
  name        text not null
                constraint bd_districts_name_check check (length(btrim(name)) between 1 and 100),
  bn_name     text,
  -- Other spellings: "Comilla", "Bogra", "Jessore".
  aliases     text[] not null default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.bd_upazilas (
  id          smallint generated by default as identity primary key,
  district_id smallint not null references public.bd_districts (id) on delete restrict,
  name        text not null
                constraint bd_upazilas_name_check check (length(btrim(name)) between 1 and 100),
  bn_name     text,
  aliases     text[] not null default '{}',
  -- 'thana' for a city's police-station areas (Dhaka's), 'upazila' otherwise.
  kind        text not null default 'upazila'
                constraint bd_upazilas_kind_check check (kind in ('upazila', 'thana')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create unique index bd_divisions_name_key on public.bd_divisions (lower(btrim(name)));
create unique index bd_districts_name_key on public.bd_districts (lower(btrim(name)));
create index bd_districts_division_idx on public.bd_districts (division_id);
-- Kaliganj, Lohagara, Nawabganj... repeat across districts, never within one.
create unique index bd_upazilas_name_key on public.bd_upazilas (district_id, lower(btrim(name)));
create index bd_upazilas_district_idx on public.bd_upazilas (district_id);

create trigger bd_divisions_set_updated_at before update on public.bd_divisions
  for each row execute function public.set_updated_at();
create trigger bd_districts_set_updated_at before update on public.bd_districts
  for each row execute function public.set_updated_at();
create trigger bd_upazilas_set_updated_at before update on public.bd_upazilas
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- RLS ---

alter table public.bd_divisions enable row level security;
alter table public.bd_districts enable row level security;
alter table public.bd_upazilas enable row level security;

create policy bd_divisions_select on public.bd_divisions for select to anon, authenticated using (true);
create policy bd_districts_select on public.bd_districts for select to anon, authenticated using (true);
create policy bd_upazilas_select on public.bd_upazilas for select to anon, authenticated using (true);

create policy bd_divisions_write on public.bd_divisions for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());
create policy bd_districts_write on public.bd_districts for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());
create policy bd_upazilas_write on public.bd_upazilas for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

-- No personal data in here, so the audit trail keeps whole rows.
select public.attach_audit('public.bd_divisions', true);
select public.attach_audit('public.bd_districts', true);
select public.attach_audit('public.bd_upazilas', true);

comment on table public.bd_divisions is 'Bangladesh''s divisions (0096). A global lookup; the super admin edits it.';
comment on table public.bd_districts is 'Bangladesh''s districts, each in a division (0096).';
comment on table public.bd_upazilas is 'Bangladesh''s upazilas, and Dhaka''s city thanas, each in a district (0096).';

-- ------------------------------------------------------------------ data ---
-- A division row is [id, name, bn_name, aliases]; a district or upazila row
-- puts its parent's id second, and an upazila ends with its kind. The ids
-- are the source dataset's; the thanas start at 1001.

insert into public.bd_divisions (id, name, bn_name, aliases)
select (r->>0)::smallint, r->>1, r->>2, array(select jsonb_array_elements_text(r->3))
from jsonb_array_elements($json$[
[1,"Chattogram","চট্টগ্রাম",["Chittagong","Chattagram"]],
[2,"Rajshahi","রাজশাহী",[]],
[3,"Khulna","খুলনা",[]],
[4,"Barishal","বরিশাল",["Barisal"]],
[5,"Sylhet","সিলেট",[]],
[6,"Dhaka","ঢাকা",[]],
[7,"Rangpur","রংপুর",[]],
[8,"Mymensingh","ময়মনসিংহ",[]]
]$json$::jsonb) r;

insert into public.bd_districts (id, division_id, name, bn_name, aliases)
select (r->>0)::smallint, (r->>1)::smallint, r->>2, r->>3, array(select jsonb_array_elements_text(r->4))
from jsonb_array_elements($json$[
[1,1,"Cumilla","কুমিল্লা",["Comilla"]],
[2,1,"Feni","ফেনী",[]],
[3,1,"Brahmanbaria","ব্রাহ্মণবাড়িয়া",["B. Baria","Brahmonbaria"]],
[4,1,"Rangamati","রাঙ্গামাটি",["Rangamati Hill District"]],
[5,1,"Noakhali","নোয়াখালী",[]],
[6,1,"Chandpur","চাঁদপুর",["Chadpur"]],
[7,1,"Lakshmipur","লক্ষ্মীপুর",["Laxmipur","Lakshipur"]],
[8,1,"Chattogram","চট্টগ্রাম",["Chittagong","Chattagram"]],
[9,1,"Cox's Bazar","কক্সবাজার",["Coxsbazar","Cox Bazar"]],
[10,1,"Khagrachhari","খাগড়াছড়ি",["Khagrachari"]],
[11,1,"Bandarban","বান্দরবান",[]],
[12,2,"Sirajganj","সিরাজগঞ্জ",["Sirajgonj"]],
[13,2,"Pabna","পাবনা",[]],
[14,2,"Bogura","বগুড়া",["Bogra"]],
[15,2,"Rajshahi","রাজশাহী",[]],
[16,2,"Natore","নাটোর",[]],
[17,2,"Joypurhat","জয়পুরহাট",["Jaipurhat"]],
[18,2,"Chapai Nawabganj","চাঁপাইনবাবগঞ্জ",["Chapainawabganj","Nawabganj"]],
[19,2,"Naogaon","নওগাঁ",[]],
[20,3,"Jashore","যশোর",["Jessore","Josher"]],
[21,3,"Satkhira","সাতক্ষীরা",[]],
[22,3,"Meherpur","মেহেরপুর",[]],
[23,3,"Narail","নড়াইল",[]],
[24,3,"Chuadanga","চুয়াডাঙ্গা",[]],
[25,3,"Kushtia","কুষ্টিয়া",[]],
[26,3,"Magura","মাগুরা",[]],
[27,3,"Khulna","খুলনা",[]],
[28,3,"Bagerhat","বাগেরহাট",[]],
[29,3,"Jhenaidah","ঝিনাইদহ",["Jhenaidaha","Jhinaidah","Jhenida"]],
[30,4,"Jhalokati","ঝালকাঠি",["Jhalakathi","Jhalokathi","Jhalakati"]],
[31,4,"Patuakhali","পটুয়াখালী",[]],
[32,4,"Pirojpur","পিরোজপুর",[]],
[33,4,"Barishal","বরিশাল",["Barisal"]],
[34,4,"Bhola","ভোলা",[]],
[35,4,"Barguna","বরগুনা",[]],
[36,5,"Sylhet","সিলেট",[]],
[37,5,"Moulvibazar","মৌলভীবাজার",["Maulvibazar","Moulvi Bazar","Maulvi Bazar"]],
[38,5,"Habiganj","হবিগঞ্জ",["Hobiganj","Habigonj"]],
[39,5,"Sunamganj","সুনামগঞ্জ",["Sunamgonj"]],
[40,6,"Narsingdi","নরসিংদী",["Narshingdi","Norsingdi"]],
[41,6,"Gazipur","গাজীপুর",[]],
[42,6,"Shariatpur","শরীয়তপুর",["Sariatpur"]],
[43,6,"Narayanganj","নারায়ণগঞ্জ",["Narayangonj"]],
[44,6,"Tangail","টাঙ্গাইল",[]],
[45,6,"Kishoreganj","কিশোরগঞ্জ",["Kishorganj","Kishoregonj"]],
[46,6,"Manikganj","মানিকগঞ্জ",["Manikgonj"]],
[47,6,"Dhaka","ঢাকা",[]],
[48,6,"Munshiganj","মুন্সিগঞ্জ",["Munshigonj"]],
[49,6,"Rajbari","রাজবাড়ী",[]],
[50,6,"Madaripur","মাদারীপুর",[]],
[51,6,"Gopalganj","গোপালগঞ্জ",["Gopalgonj"]],
[52,6,"Faridpur","ফরিদপুর",[]],
[53,7,"Panchagarh","পঞ্চগড়",["Panchagar"]],
[54,7,"Dinajpur","দিনাজপুর",[]],
[55,7,"Lalmonirhat","লালমনিরহাট",[]],
[56,7,"Nilphamari","নীলফামারী",[]],
[57,7,"Gaibandha","গাইবান্ধা",["Gaibanda"]],
[58,7,"Thakurgaon","ঠাকুরগাঁও",["Thakurgoan"]],
[59,7,"Rangpur","রংপুর",[]],
[60,7,"Kurigram","কুড়িগ্রাম",[]],
[61,8,"Sherpur","শেরপুর",[]],
[62,8,"Mymensingh","ময়মনসিংহ",["Mymensing","Moymonsingh"]],
[63,8,"Jamalpur","জামালপুর",[]],
[64,8,"Netrokona","নেত্রকোণা",["Netrakona"]]
]$json$::jsonb) r;

insert into public.bd_upazilas (id, district_id, name, bn_name, aliases, kind)
select (r->>0)::smallint, (r->>1)::smallint, r->>2, r->>3, array(select jsonb_array_elements_text(r->4)), r->>5
from jsonb_array_elements($json$[
[1,1,"Debidwar","দেবিদ্বার",[],"upazila"],
[2,1,"Barura","বরুড়া",[],"upazila"],
[3,1,"Brahmanpara","ব্রাহ্মণপাড়া",[],"upazila"],
[4,1,"Chandina","চান্দিনা",[],"upazila"],
[5,1,"Chauddagram","চৌদ্দগ্রাম",[],"upazila"],
[6,1,"Daudkandi","দাউদকান্দি",[],"upazila"],
[7,1,"Homna","হোমনা",[],"upazila"],
[8,1,"Laksam","লাকসাম",[],"upazila"],
[9,1,"Muradnagar","মুরাদনগর",[],"upazila"],
[10,1,"Nangalkot","নাঙ্গলকোট",[],"upazila"],
[11,1,"Cumilla Adarsha Sadar","কুমিল্লা সদর",["Comilla Sadar","Cumilla Sadar","Comilla Adarsha Sadar"],"upazila"],
[12,1,"Meghna","মেঘনা",[],"upazila"],
[13,1,"Manoharganj","মনোহরগঞ্জ",["Monohargonj","Monohorgonj"],"upazila"],
[14,1,"Cumilla Sadar Dakshin","সদর দক্ষিণ",["Sadar South","Sadarsouth","Comilla Sadar Dakshin"],"upazila"],
[15,1,"Titas","তিতাস",[],"upazila"],
[16,1,"Burichang","বুড়িচং",[],"upazila"],
[17,1,"Lalmai","লালমাই",[],"upazila"],
[18,2,"Chhagalnaiya","ছাগলনাইয়া",[],"upazila"],
[19,2,"Feni Sadar","ফেনী সদর",[],"upazila"],
[20,2,"Sonagazi","সোনাগাজী",[],"upazila"],
[21,2,"Fulgazi","ফুলগাজী",[],"upazila"],
[22,2,"Parshuram","পরশুরাম",[],"upazila"],
[23,2,"Daganbhuiyan","দাগনভূঞা",[],"upazila"],
[24,3,"Brahmanbaria Sadar","ব্রাহ্মণবাড়িয়া সদর",[],"upazila"],
[25,3,"Kasba","কসবা",[],"upazila"],
[26,3,"Nasirnagar","নাসিরনগর",[],"upazila"],
[27,3,"Sarail","সরাইল",[],"upazila"],
[28,3,"Ashuganj","আশুগঞ্জ",[],"upazila"],
[29,3,"Akhaura","আখাউড়া",[],"upazila"],
[30,3,"Nabinagar","নবীনগর",[],"upazila"],
[31,3,"Bancharampur","বাঞ্ছারামপুর",[],"upazila"],
[32,3,"Bijoynagar","বিজয়নগর",[],"upazila"],
[33,4,"Rangamati Sadar","রাঙ্গামাটি সদর",[],"upazila"],
[34,4,"Kaptai","কাপ্তাই",[],"upazila"],
[35,4,"Kawkhali","কাউখালী",[],"upazila"],
[36,4,"Baghaichhari","বাঘাইছড়ি",["Baghaichari"],"upazila"],
[37,4,"Barkal","বরকল",[],"upazila"],
[38,4,"Langadu","লংগদু",[],"upazila"],
[39,4,"Rajasthali","রাজস্থলী",[],"upazila"],
[40,4,"Belaichari","বিলাইছড়ি",[],"upazila"],
[41,4,"Jurachhari","জুরাছড়ি",["Juraichari"],"upazila"],
[42,4,"Naniarchar","নানিয়ারচর",[],"upazila"],
[43,5,"Noakhali Sadar","নোয়াখালী সদর",[],"upazila"],
[44,5,"Companiganj","কোম্পানীগঞ্জ",[],"upazila"],
[45,5,"Begumganj","বেগমগঞ্জ",[],"upazila"],
[46,5,"Hatia","হাতিয়া",[],"upazila"],
[47,5,"Subarnachar","সুবর্ণচর",[],"upazila"],
[48,5,"Kabirhat","কবিরহাট",[],"upazila"],
[49,5,"Senbagh","সেনবাগ",["Senbug"],"upazila"],
[50,5,"Chatkhil","চাটখিল",[],"upazila"],
[51,5,"Sonaimuri","সোনাইমুড়ী",["Sonaimori"],"upazila"],
[52,6,"Haimchar","হাইমচর",[],"upazila"],
[53,6,"Kachua","কচুয়া",[],"upazila"],
[54,6,"Shahrasti","শাহরাস্তি",[],"upazila"],
[55,6,"Chandpur Sadar","চাঁদপুর সদর",[],"upazila"],
[56,6,"Matlab Dakshin","মতলব দক্ষিণ",["Matlab South"],"upazila"],
[57,6,"Hajiganj","হাজীগঞ্জ",[],"upazila"],
[58,6,"Matlab Uttar","মতলব উত্তর",["Matlab North"],"upazila"],
[59,6,"Faridganj","ফরিদগঞ্জ",["Faridgonj"],"upazila"],
[60,7,"Lakshmipur Sadar","লক্ষ্মীপুর সদর",[],"upazila"],
[61,7,"Kamalnagar","কমলনগর",[],"upazila"],
[62,7,"Raipur","রায়পুর",[],"upazila"],
[63,7,"Ramgati","রামগতি",[],"upazila"],
[64,7,"Ramganj","রামগঞ্জ",[],"upazila"],
[65,8,"Rangunia","রাঙ্গুনিয়া",[],"upazila"],
[66,8,"Sitakunda","সীতাকুন্ড",[],"upazila"],
[67,8,"Mirsharai","মীরসরাই",[],"upazila"],
[68,8,"Patiya","পটিয়া",[],"upazila"],
[69,8,"Sandwip","সন্দ্বীপ",[],"upazila"],
[70,8,"Banshkhali","বাঁশখালী",[],"upazila"],
[71,8,"Boalkhali","বোয়ালখালী",[],"upazila"],
[72,8,"Anwara","আনোয়ারা",[],"upazila"],
[73,8,"Chandanaish","চন্দনাইশ",[],"upazila"],
[74,8,"Satkania","সাতকানিয়া",[],"upazila"],
[75,8,"Lohagara","লোহাগাড়া",[],"upazila"],
[76,8,"Hathazari","হাটহাজারী",[],"upazila"],
[77,8,"Fatikchhari","ফটিকছড়ি",[],"upazila"],
[78,8,"Raozan","রাউজান",[],"upazila"],
[79,8,"Karnaphuli","কর্ণফুলী",["Karnafuli"],"upazila"],
[80,9,"Cox's Bazar Sadar","কক্সবাজার সদর",["Coxsbazar Sadar"],"upazila"],
[81,9,"Chakaria","চকরিয়া",[],"upazila"],
[82,9,"Kutubdia","কুতুবদিয়া",[],"upazila"],
[83,9,"Ukhia","উখিয়া",["Ukhiya"],"upazila"],
[84,9,"Maheshkhali","মহেশখালী",["Moheshkhali"],"upazila"],
[85,9,"Pekua","পেকুয়া",[],"upazila"],
[86,9,"Ramu","রামু",[],"upazila"],
[87,9,"Teknaf","টেকনাফ",[],"upazila"],
[88,10,"Khagrachhari Sadar","খাগড়াছড়ি সদর",[],"upazila"],
[89,10,"Dighinala","দিঘীনালা",[],"upazila"],
[90,10,"Panchari","পানছড়ি",[],"upazila"],
[91,10,"Lakshmichhari","লক্ষীছড়ি",["Laxmichhari"],"upazila"],
[92,10,"Mohalchari","মহালছড়ি",[],"upazila"],
[93,10,"Manikchari","মানিকছড়ি",[],"upazila"],
[94,10,"Ramgarh","রামগড়",[],"upazila"],
[95,10,"Matiranga","মাটিরাঙ্গা",[],"upazila"],
[96,10,"Guimara","গুইমারা",[],"upazila"],
[97,11,"Bandarban Sadar","বান্দরবান সদর",[],"upazila"],
[98,11,"Alikadam","আলীকদম",[],"upazila"],
[99,11,"Naikhongchhari","নাইক্ষ্যংছড়ি",[],"upazila"],
[100,11,"Rowangchhari","রোয়াংছড়ি",[],"upazila"],
[101,11,"Lama","লামা",[],"upazila"],
[102,11,"Ruma","রুমা",[],"upazila"],
[103,11,"Thanchi","থানচি",[],"upazila"],
[104,12,"Belkuchi","বেলকুচি",[],"upazila"],
[105,12,"Chauhali","চৌহালি",[],"upazila"],
[106,12,"Kamarkhand","কামারখন্দ",[],"upazila"],
[107,12,"Kazipur","কাজীপুর",[],"upazila"],
[108,12,"Raiganj","রায়গঞ্জ",["Raigonj"],"upazila"],
[109,12,"Shahjadpur","শাহজাদপুর",[],"upazila"],
[110,12,"Sirajganj Sadar","সিরাজগঞ্জ সদর",[],"upazila"],
[111,12,"Tarash","তাড়াশ",[],"upazila"],
[112,12,"Ullapara","উল্লাপাড়া",[],"upazila"],
[113,13,"Sujanagar","সুজানগর",[],"upazila"],
[114,13,"Ishurdi","ঈশ্বরদী",[],"upazila"],
[115,13,"Bhangura","ভাঙ্গুড়া",[],"upazila"],
[116,13,"Pabna Sadar","পাবনা সদর",[],"upazila"],
[117,13,"Bera","বেড়া",[],"upazila"],
[118,13,"Atghoria","আটঘরিয়া",[],"upazila"],
[119,13,"Chatmohar","চাটমোহর",[],"upazila"],
[120,13,"Santhia","সাঁথিয়া",[],"upazila"],
[121,13,"Faridpur","ফরিদপুর",[],"upazila"],
[122,14,"Kahaloo","কাহালু",["Kahalu"],"upazila"],
[123,14,"Bogura Sadar","বগুড়া সদর",["Bogra Sadar"],"upazila"],
[124,14,"Shariakandi","সারিয়াকান্দি",[],"upazila"],
[125,14,"Shajahanpur","শাজাহানপুর",[],"upazila"],
[126,14,"Dupchanchia","দুপচাচিঁয়া",[],"upazila"],
[127,14,"Adamdighi","আদমদিঘি",[],"upazila"],
[128,14,"Nandigram","নন্দিগ্রাম",["Nondigram"],"upazila"],
[129,14,"Sonatala","সোনাতলা",[],"upazila"],
[130,14,"Dhunot","ধুনট",[],"upazila"],
[131,14,"Gabtali","গাবতলী",[],"upazila"],
[132,14,"Sherpur","শেরপুর",[],"upazila"],
[133,14,"Shibganj","শিবগঞ্জ",[],"upazila"],
[134,15,"Paba","পবা",[],"upazila"],
[135,15,"Durgapur","দুর্গাপুর",[],"upazila"],
[136,15,"Mohanpur","মোহনপুর",["Mohonpur"],"upazila"],
[137,15,"Charghat","চারঘাট",[],"upazila"],
[138,15,"Puthia","পুঠিয়া",[],"upazila"],
[139,15,"Bagha","বাঘা",[],"upazila"],
[140,15,"Godagari","গোদাগাড়ী",[],"upazila"],
[141,15,"Tanore","তানোর",[],"upazila"],
[142,15,"Bagmara","বাগমারা",[],"upazila"],
[143,16,"Natore Sadar","নাটোর সদর",[],"upazila"],
[144,16,"Singra","সিংড়া",[],"upazila"],
[145,16,"Baraigram","বড়াইগ্রাম",[],"upazila"],
[146,16,"Bagatipara","বাগাতিপাড়া",[],"upazila"],
[147,16,"Lalpur","লালপুর",[],"upazila"],
[148,16,"Gurudaspur","গুরুদাসপুর",[],"upazila"],
[149,16,"Naldanga","নলডাঙ্গা",[],"upazila"],
[150,17,"Akkelpur","আক্কেলপুর",[],"upazila"],
[151,17,"Kalai","কালাই",[],"upazila"],
[152,17,"Khetlal","ক্ষেতলাল",[],"upazila"],
[153,17,"Panchbibi","পাঁচবিবি",[],"upazila"],
[154,17,"Joypurhat Sadar","জয়পুরহাট সদর",[],"upazila"],
[155,18,"Chapai Nawabganj Sadar","চাঁপাইনবাবগঞ্জ সদর",["Chapainawabganj Sadar","Nawabganj Sadar"],"upazila"],
[156,18,"Gomastapur","গোমস্তাপুর",["Gomostapur"],"upazila"],
[157,18,"Nachol","নাচোল",[],"upazila"],
[158,18,"Bholahat","ভোলাহাট",[],"upazila"],
[159,18,"Shibganj","শিবগঞ্জ",[],"upazila"],
[160,19,"Mahadebpur","মহাদেবপুর",["Mohadevpur","Mahadevpur"],"upazila"],
[161,19,"Badalgachi","বদলগাছী",[],"upazila"],
[162,19,"Patnitala","পত্নিতলা",[],"upazila"],
[163,19,"Dhamoirhat","ধামইরহাট",[],"upazila"],
[164,19,"Niamatpur","নিয়ামতপুর",[],"upazila"],
[165,19,"Manda","মান্দা",[],"upazila"],
[166,19,"Atrai","আত্রাই",[],"upazila"],
[167,19,"Raninagar","রাণীনগর",[],"upazila"],
[168,19,"Naogaon Sadar","নওগাঁ সদর",[],"upazila"],
[169,19,"Porsha","পোরশা",[],"upazila"],
[170,19,"Sapahar","সাপাহার",[],"upazila"],
[171,20,"Manirampur","মণিরামপুর",[],"upazila"],
[172,20,"Abhaynagar","অভয়নগর",[],"upazila"],
[173,20,"Bagherpara","বাঘারপাড়া",[],"upazila"],
[174,20,"Chougachha","চৌগাছা",[],"upazila"],
[175,20,"Jhikargachha","ঝিকরগাছা",["Jhikargacha"],"upazila"],
[176,20,"Keshabpur","কেশবপুর",[],"upazila"],
[177,20,"Jashore Sadar","যশোর সদর",["Jessore Sadar"],"upazila"],
[178,20,"Sharsha","শার্শা",[],"upazila"],
[179,21,"Assasuni","আশাশুনি",[],"upazila"],
[180,21,"Debhata","দেবহাটা",[],"upazila"],
[181,21,"Kalaroa","কলারোয়া",[],"upazila"],
[182,21,"Satkhira Sadar","সাতক্ষীরা সদর",[],"upazila"],
[183,21,"Shyamnagar","শ্যামনগর",[],"upazila"],
[184,21,"Tala","তালা",[],"upazila"],
[185,21,"Kaliganj","কালিগঞ্জ",[],"upazila"],
[186,22,"Mujibnagar","মুজিবনগর",[],"upazila"],
[187,22,"Meherpur Sadar","মেহেরপুর সদর",[],"upazila"],
[188,22,"Gangni","গাংনী",[],"upazila"],
[189,23,"Narail Sadar","নড়াইল সদর",[],"upazila"],
[190,23,"Lohagara","লোহাগড়া",[],"upazila"],
[191,23,"Kalia","কালিয়া",[],"upazila"],
[192,24,"Chuadanga Sadar","চুয়াডাঙ্গা সদর",[],"upazila"],
[193,24,"Alamdanga","আলমডাঙ্গা",[],"upazila"],
[194,24,"Damurhuda","দামুড়হুদা",[],"upazila"],
[195,24,"Jibannagar","জীবননগর",[],"upazila"],
[196,25,"Kushtia Sadar","কুষ্টিয়া সদর",[],"upazila"],
[197,25,"Kumarkhali","কুমারখালী",[],"upazila"],
[198,25,"Khoksa","খোকসা",[],"upazila"],
[199,25,"Mirpur","মিরপুর",[],"upazila"],
[200,25,"Daulatpur","দৌলতপুর",[],"upazila"],
[201,25,"Bheramara","ভেড়ামারা",[],"upazila"],
[202,26,"Shalikha","শালিখা",[],"upazila"],
[203,26,"Sreepur","শ্রীপুর",[],"upazila"],
[204,26,"Magura Sadar","মাগুরা সদর",[],"upazila"],
[205,26,"Mohammadpur","মহম্মদপুর",[],"upazila"],
[206,27,"Paikgachha","পাইকগাছা",["Paikgasa","Paikgacha"],"upazila"],
[207,27,"Phultala","ফুলতলা",["Fultola"],"upazila"],
[208,27,"Dighalia","দিঘলিয়া",["Digholia"],"upazila"],
[209,27,"Rupsa","রূপসা",["Rupsha"],"upazila"],
[210,27,"Terokhada","তেরখাদা",[],"upazila"],
[211,27,"Dumuria","ডুমুরিয়া",[],"upazila"],
[212,27,"Batiaghata","বটিয়াঘাটা",["Botiaghata"],"upazila"],
[213,27,"Dacope","দাকোপ",["Dakop"],"upazila"],
[214,27,"Koyra","কয়রা",[],"upazila"],
[215,28,"Fakirhat","ফকিরহাট",[],"upazila"],
[216,28,"Bagerhat Sadar","বাগেরহাট সদর",[],"upazila"],
[217,28,"Mollahat","মোল্লাহাট",[],"upazila"],
[218,28,"Sarankhola","শরণখোলা",[],"upazila"],
[219,28,"Rampal","রামপাল",[],"upazila"],
[220,28,"Morrelganj","মোড়েলগঞ্জ",[],"upazila"],
[221,28,"Kachua","কচুয়া",[],"upazila"],
[222,28,"Mongla","মোংলা",[],"upazila"],
[223,28,"Chitalmari","চিতলমারী",[],"upazila"],
[224,29,"Jhenaidah Sadar","ঝিনাইদহ সদর",[],"upazila"],
[225,29,"Shailkupa","শৈলকুপা",[],"upazila"],
[226,29,"Harinakundu","হরিণাকুন্ডু",[],"upazila"],
[227,29,"Kaliganj","কালীগঞ্জ",[],"upazila"],
[228,29,"Kotchandpur","কোটচাঁদপুর",[],"upazila"],
[229,29,"Maheshpur","মহেশপুর",["Moheshpur"],"upazila"],
[230,30,"Jhalokati Sadar","ঝালকাঠি সদর",["Jhalakathi Sadar"],"upazila"],
[231,30,"Kathalia","কাঠালিয়া",[],"upazila"],
[232,30,"Nalchity","নলছিটি",[],"upazila"],
[233,30,"Rajapur","রাজাপুর",[],"upazila"],
[234,31,"Bauphal","বাউফল",[],"upazila"],
[235,31,"Patuakhali Sadar","পটুয়াখালী সদর",[],"upazila"],
[236,31,"Dumki","দুমকি",[],"upazila"],
[237,31,"Dashmina","দশমিনা",[],"upazila"],
[238,31,"Kalapara","কলাপাড়া",[],"upazila"],
[239,31,"Mirzaganj","মির্জাগঞ্জ",[],"upazila"],
[240,31,"Galachipa","গলাচিপা",[],"upazila"],
[241,31,"Rangabali","রাঙ্গাবালী",[],"upazila"],
[242,32,"Pirojpur Sadar","পিরোজপুর সদর",[],"upazila"],
[243,32,"Nazirpur","নাজিরপুর",[],"upazila"],
[244,32,"Kawkhali","কাউখালী",[],"upazila"],
[245,32,"Indurkani","ইন্দুরকানী",["Zianagar","জিয়ানগর"],"upazila"],
[246,32,"Bhandaria","ভান্ডারিয়া",[],"upazila"],
[247,32,"Mathbaria","মঠবাড়ীয়া",[],"upazila"],
[248,32,"Nesarabad","নেছারাবাদ",[],"upazila"],
[249,33,"Barishal Sadar","বরিশাল সদর",["Barisal Sadar"],"upazila"],
[250,33,"Bakerganj","বাকেরগঞ্জ",[],"upazila"],
[251,33,"Babuganj","বাবুগঞ্জ",[],"upazila"],
[252,33,"Wazirpur","উজিরপুর",[],"upazila"],
[253,33,"Banaripara","বানারীপাড়া",[],"upazila"],
[254,33,"Gaurnadi","গৌরনদী",["Gournadi"],"upazila"],
[255,33,"Agailjhara","আগৈলঝাড়া",[],"upazila"],
[256,33,"Mehendiganj","মেহেন্দিগঞ্জ",[],"upazila"],
[257,33,"Muladi","মুলাদী",[],"upazila"],
[258,33,"Hizla","হিজলা",[],"upazila"],
[259,34,"Bhola Sadar","ভোলা সদর",[],"upazila"],
[260,34,"Burhanuddin","বোরহান উদ্দিন",["Borhanuddin","Borhan Uddin","Borhan Sddin"],"upazila"],
[261,34,"Char Fasson","চরফ্যাশন",["Charfesson","Charfasson"],"upazila"],
[262,34,"Daulatkhan","দৌলতখান",["Doulatkhan"],"upazila"],
[263,34,"Monpura","মনপুরা",[],"upazila"],
[264,34,"Tazumuddin","তজুমদ্দিন",[],"upazila"],
[265,34,"Lalmohan","লালমোহন",[],"upazila"],
[266,35,"Amtali","আমতলী",[],"upazila"],
[267,35,"Barguna Sadar","বরগুনা সদর",[],"upazila"],
[268,35,"Betagi","বেতাগী",[],"upazila"],
[269,35,"Bamna","বামনা",[],"upazila"],
[270,35,"Patharghata","পাথরঘাটা",["Pathorghata"],"upazila"],
[271,35,"Taltali","তালতলি",[],"upazila"],
[272,36,"Balaganj","বালাগঞ্জ",[],"upazila"],
[273,36,"Beanibazar","বিয়ানীবাজার",[],"upazila"],
[274,36,"Bishwanath","বিশ্বনাথ",[],"upazila"],
[275,36,"Companiganj","কোম্পানীগঞ্জ",[],"upazila"],
[276,36,"Fenchuganj","ফেঞ্চুগঞ্জ",[],"upazila"],
[277,36,"Golapganj","গোলাপগঞ্জ",[],"upazila"],
[278,36,"Gowainghat","গোয়াইনঘাট",[],"upazila"],
[279,36,"Jaintiapur","জৈন্তাপুর",[],"upazila"],
[280,36,"Kanaighat","কানাইঘাট",[],"upazila"],
[281,36,"Sylhet Sadar","সিলেট সদর",[],"upazila"],
[282,36,"Zakiganj","জকিগঞ্জ",[],"upazila"],
[283,36,"Dakshin Surma","দক্ষিণ সুরমা",["Dakshinsurma","South Surma"],"upazila"],
[284,36,"Osmaninagar","ওসমানী নগর",[],"upazila"],
[285,37,"Barlekha","বড়লেখা",[],"upazila"],
[286,37,"Kamalganj","কমলগঞ্জ",["Kamolganj"],"upazila"],
[287,37,"Kulaura","কুলাউড়া",[],"upazila"],
[288,37,"Moulvibazar Sadar","মৌলভীবাজার সদর",[],"upazila"],
[289,37,"Rajnagar","রাজনগর",[],"upazila"],
[290,37,"Sreemangal","শ্রীমঙ্গল",["Srimangal"],"upazila"],
[291,37,"Juri","জুড়ী",[],"upazila"],
[292,38,"Nabiganj","নবীগঞ্জ",[],"upazila"],
[293,38,"Bahubal","বাহুবল",[],"upazila"],
[294,38,"Ajmiriganj","আজমিরীগঞ্জ",[],"upazila"],
[295,38,"Baniachong","বানিয়াচং",["Baniachang"],"upazila"],
[296,38,"Lakhai","লাখাই",[],"upazila"],
[297,38,"Chunarughat","চুনারুঘাট",[],"upazila"],
[298,38,"Habiganj Sadar","হবিগঞ্জ সদর",[],"upazila"],
[299,38,"Madhabpur","মাধবপুর",[],"upazila"],
[300,39,"Sunamganj Sadar","সুনামগঞ্জ সদর",[],"upazila"],
[301,39,"Shantiganj","শান্তিগঞ্জ",["South Sunamganj","Dakshin Sunamganj","দক্ষিণ সুনামগঞ্জ"],"upazila"],
[302,39,"Bishwambarpur","বিশ্বম্ভরপুর",[],"upazila"],
[303,39,"Chhatak","ছাতক",[],"upazila"],
[304,39,"Jagannathpur","জগন্নাথপুর",[],"upazila"],
[305,39,"Dowarabazar","দোয়ারাবাজার",[],"upazila"],
[306,39,"Tahirpur","তাহিরপুর",[],"upazila"],
[307,39,"Dharmapasha","ধর্মপাশা",[],"upazila"],
[308,39,"Jamalganj","জামালগঞ্জ",[],"upazila"],
[309,39,"Shalla","শাল্লা",[],"upazila"],
[310,39,"Derai","দিরাই",[],"upazila"],
[311,40,"Belabo","বেলাবো",[],"upazila"],
[312,40,"Monohardi","মনোহরদী",[],"upazila"],
[313,40,"Narsingdi Sadar","নরসিংদী সদর",[],"upazila"],
[314,40,"Palash","পলাশ",[],"upazila"],
[315,40,"Raipura","রায়পুরা",[],"upazila"],
[316,40,"Shibpur","শিবপুর",[],"upazila"],
[317,41,"Kaliganj","কালীগঞ্জ",[],"upazila"],
[318,41,"Kaliakair","কালিয়াকৈর",[],"upazila"],
[319,41,"Kapasia","কাপাসিয়া",[],"upazila"],
[320,41,"Gazipur Sadar","গাজীপুর সদর",[],"upazila"],
[321,41,"Sreepur","শ্রীপুর",[],"upazila"],
[322,42,"Shariatpur Sadar","শরিয়তপুর সদর",[],"upazila"],
[323,42,"Naria","নড়িয়া",[],"upazila"],
[324,42,"Zanjira","জাজিরা",["Zajira","Jajira"],"upazila"],
[325,42,"Gosairhat","গোসাইরহাট",[],"upazila"],
[326,42,"Bhedarganj","ভেদরগঞ্জ",[],"upazila"],
[327,42,"Damudya","ডামুড্যা",[],"upazila"],
[328,43,"Araihazar","আড়াইহাজার",[],"upazila"],
[329,43,"Bandar","বন্দর",[],"upazila"],
[330,43,"Narayanganj Sadar","নারায়নগঞ্জ সদর",[],"upazila"],
[331,43,"Rupganj","রূপগঞ্জ",[],"upazila"],
[332,43,"Sonargaon","সোনারগাঁ",[],"upazila"],
[333,44,"Basail","বাসাইল",[],"upazila"],
[334,44,"Bhuapur","ভুয়াপুর",[],"upazila"],
[335,44,"Delduar","দেলদুয়ার",[],"upazila"],
[336,44,"Ghatail","ঘাটাইল",[],"upazila"],
[337,44,"Gopalpur","গোপালপুর",[],"upazila"],
[338,44,"Madhupur","মধুপুর",[],"upazila"],
[339,44,"Mirzapur","মির্জাপুর",[],"upazila"],
[340,44,"Nagarpur","নাগরপুর",[],"upazila"],
[341,44,"Sakhipur","সখিপুর",[],"upazila"],
[342,44,"Tangail Sadar","টাঙ্গাইল সদর",[],"upazila"],
[343,44,"Kalihati","কালিহাতী",[],"upazila"],
[344,44,"Dhanbari","ধনবাড়ী",[],"upazila"],
[345,45,"Itna","ইটনা",[],"upazila"],
[346,45,"Katiadi","কটিয়াদী",[],"upazila"],
[347,45,"Bhairab","ভৈরব",[],"upazila"],
[348,45,"Tarail","তাড়াইল",[],"upazila"],
[349,45,"Hossainpur","হোসেনপুর",[],"upazila"],
[350,45,"Pakundia","পাকুন্দিয়া",[],"upazila"],
[351,45,"Kuliarchar","কুলিয়ারচর",[],"upazila"],
[352,45,"Kishoreganj Sadar","কিশোরগঞ্জ সদর",[],"upazila"],
[353,45,"Karimganj","করিমগঞ্জ",["Karimgonj"],"upazila"],
[354,45,"Bajitpur","বাজিতপুর",[],"upazila"],
[355,45,"Austagram","অষ্টগ্রাম",["Astagram"],"upazila"],
[356,45,"Mithamain","মিঠামইন",["Mithamoin"],"upazila"],
[357,45,"Nikli","নিকলী",[],"upazila"],
[358,46,"Harirampur","হরিরামপুর",[],"upazila"],
[359,46,"Saturia","সাটুরিয়া",[],"upazila"],
[360,46,"Manikganj Sadar","মানিকগঞ্জ সদর",[],"upazila"],
[361,46,"Ghior","ঘিওর",["Gior"],"upazila"],
[362,46,"Shivalaya","শিবালয়",["Shibaloy","Shibalaya"],"upazila"],
[363,46,"Daulatpur","দৌলতপুর",["Doulatpur"],"upazila"],
[364,46,"Singair","সিংগাইর",["Singiar"],"upazila"],
[365,47,"Savar","সাভার",[],"upazila"],
[366,47,"Dhamrai","ধামরাই",[],"upazila"],
[367,47,"Keraniganj","কেরাণীগঞ্জ",[],"upazila"],
[368,47,"Nawabganj","নবাবগঞ্জ",[],"upazila"],
[369,47,"Dohar","দোহার",[],"upazila"],
[370,48,"Munshiganj Sadar","মুন্সিগঞ্জ সদর",[],"upazila"],
[371,48,"Sreenagar","শ্রীনগর",[],"upazila"],
[372,48,"Sirajdikhan","সিরাজদিখান",[],"upazila"],
[373,48,"Lohajang","লৌহজং",["Louhajanj","Louhajang"],"upazila"],
[374,48,"Gajaria","গজারিয়া",[],"upazila"],
[375,48,"Tongibari","টংগীবাড়ি",[],"upazila"],
[376,49,"Rajbari Sadar","রাজবাড়ী সদর",[],"upazila"],
[377,49,"Goalanda","গোয়ালন্দ",[],"upazila"],
[378,49,"Pangsa","পাংশা",[],"upazila"],
[379,49,"Baliakandi","বালিয়াকান্দি",[],"upazila"],
[380,49,"Kalukhali","কালুখালী",[],"upazila"],
[381,50,"Madaripur Sadar","মাদারীপুর সদর",[],"upazila"],
[382,50,"Shibchar","শিবচর",[],"upazila"],
[383,50,"Kalkini","কালকিনি",[],"upazila"],
[384,50,"Rajoir","রাজৈর",[],"upazila"],
[385,51,"Gopalganj Sadar","গোপালগঞ্জ সদর",[],"upazila"],
[386,51,"Kashiani","কাশিয়ানী",[],"upazila"],
[387,51,"Tungipara","টুংগীপাড়া",[],"upazila"],
[388,51,"Kotalipara","কোটালীপাড়া",[],"upazila"],
[389,51,"Muksudpur","মুকসুদপুর",[],"upazila"],
[390,52,"Faridpur Sadar","ফরিদপুর সদর",[],"upazila"],
[391,52,"Alfadanga","আলফাডাঙ্গা",[],"upazila"],
[392,52,"Boalmari","বোয়ালমারী",[],"upazila"],
[393,52,"Sadarpur","সদরপুর",[],"upazila"],
[394,52,"Nagarkanda","নগরকান্দা",[],"upazila"],
[395,52,"Bhanga","ভাঙ্গা",[],"upazila"],
[396,52,"Charbhadrasan","চরভদ্রাসন",[],"upazila"],
[397,52,"Madhukhali","মধুখালী",[],"upazila"],
[398,52,"Saltha","সালথা",[],"upazila"],
[399,53,"Panchagarh Sadar","পঞ্চগড় সদর",[],"upazila"],
[400,53,"Debiganj","দেবীগঞ্জ",[],"upazila"],
[401,53,"Boda","বোদা",[],"upazila"],
[402,53,"Atwari","আটোয়ারী",[],"upazila"],
[403,53,"Tetulia","তেতুলিয়া",["Tentulia"],"upazila"],
[404,54,"Nawabganj","নবাবগঞ্জ",[],"upazila"],
[405,54,"Birganj","বীরগঞ্জ",[],"upazila"],
[406,54,"Ghoraghat","ঘোড়াঘাট",[],"upazila"],
[407,54,"Birampur","বিরামপুর",[],"upazila"],
[408,54,"Parbatipur","পার্বতীপুর",[],"upazila"],
[409,54,"Bochaganj","বোচাগঞ্জ",[],"upazila"],
[410,54,"Kaharol","কাহারোল",[],"upazila"],
[411,54,"Fulbari","ফুলবাড়ী",[],"upazila"],
[412,54,"Dinajpur Sadar","দিনাজপুর সদর",[],"upazila"],
[413,54,"Hakimpur","হাকিমপুর",[],"upazila"],
[414,54,"Khansama","খানসামা",[],"upazila"],
[415,54,"Biral","বিরল",["Birol"],"upazila"],
[416,54,"Chirirbandar","চিরিরবন্দর",[],"upazila"],
[417,55,"Lalmonirhat Sadar","লালমনিরহাট সদর",[],"upazila"],
[418,55,"Kaliganj","কালীগঞ্জ",[],"upazila"],
[419,55,"Hatibandha","হাতীবান্ধা",[],"upazila"],
[420,55,"Patgram","পাটগ্রাম",[],"upazila"],
[421,55,"Aditmari","আদিতমারী",[],"upazila"],
[422,56,"Saidpur","সৈয়দপুর",["Syedpur"],"upazila"],
[423,56,"Domar","ডোমার",[],"upazila"],
[424,56,"Dimla","ডিমলা",[],"upazila"],
[425,56,"Jaldhaka","জলঢাকা",[],"upazila"],
[426,56,"Kishorganj","কিশোরগঞ্জ",[],"upazila"],
[427,56,"Nilphamari Sadar","নীলফামারী সদর",[],"upazila"],
[428,57,"Sadullapur","সাদুল্লাপুর",[],"upazila"],
[429,57,"Gaibandha Sadar","গাইবান্ধা সদর",[],"upazila"],
[430,57,"Palashbari","পলাশবাড়ী",[],"upazila"],
[431,57,"Saghata","সাঘাটা",[],"upazila"],
[432,57,"Gobindaganj","গোবিন্দগঞ্জ",[],"upazila"],
[433,57,"Sundarganj","সুন্দরগঞ্জ",[],"upazila"],
[434,57,"Phulchari","ফুলছড়ি",[],"upazila"],
[435,58,"Thakurgaon Sadar","ঠাকুরগাঁও সদর",[],"upazila"],
[436,58,"Pirganj","পীরগঞ্জ",[],"upazila"],
[437,58,"Ranisankail","রাণীশংকৈল",[],"upazila"],
[438,58,"Haripur","হরিপুর",[],"upazila"],
[439,58,"Baliadangi","বালিয়াডাঙ্গী",[],"upazila"],
[440,59,"Rangpur Sadar","রংপুর সদর",[],"upazila"],
[441,59,"Gangachara","গংগাচড়া",[],"upazila"],
[442,59,"Taraganj","তারাগঞ্জ",["Taragonj"],"upazila"],
[443,59,"Badarganj","বদরগঞ্জ",["Badargonj"],"upazila"],
[444,59,"Mithapukur","মিঠাপুকুর",[],"upazila"],
[445,59,"Pirganj","পীরগঞ্জ",["Pirgonj"],"upazila"],
[446,59,"Kaunia","কাউনিয়া",[],"upazila"],
[447,59,"Pirgachha","পীরগাছা",["Pirgacha"],"upazila"],
[448,60,"Kurigram Sadar","কুড়িগ্রাম সদর",[],"upazila"],
[449,60,"Nageshwari","নাগেশ্বরী",[],"upazila"],
[450,60,"Bhurungamari","ভুরুঙ্গামারী",[],"upazila"],
[451,60,"Phulbari","ফুলবাড়ী",[],"upazila"],
[452,60,"Rajarhat","রাজারহাট",[],"upazila"],
[453,60,"Ulipur","উলিপুর",[],"upazila"],
[454,60,"Chilmari","চিলমারী",[],"upazila"],
[455,60,"Raumari","রৌমারী",["Rowmari"],"upazila"],
[456,60,"Char Rajibpur","চর রাজিবপুর",["Charrajibpur"],"upazila"],
[457,61,"Sherpur Sadar","শেরপুর সদর",[],"upazila"],
[458,61,"Nalitabari","নালিতাবাড়ী",[],"upazila"],
[459,61,"Sreebardi","শ্রীবরদী",["Sreebordi"],"upazila"],
[460,61,"Nakla","নকলা",["Nokla"],"upazila"],
[461,61,"Jhenaigati","ঝিনাইগাতী",[],"upazila"],
[462,62,"Phulbaria","ফুলবাড়ীয়া",["Fulbaria"],"upazila"],
[463,62,"Trishal","ত্রিশাল",[],"upazila"],
[464,62,"Bhaluka","ভালুকা",[],"upazila"],
[465,62,"Muktagachha","মুক্তাগাছা",["Muktagacha"],"upazila"],
[466,62,"Mymensingh Sadar","ময়মনসিংহ সদর",[],"upazila"],
[467,62,"Dhobaura","ধোবাউড়া",[],"upazila"],
[468,62,"Phulpur","ফুলপুর",["Fulpur"],"upazila"],
[469,62,"Haluaghat","হালুয়াঘাট",[],"upazila"],
[470,62,"Gauripur","গৌরীপুর",["Gouripur"],"upazila"],
[471,62,"Gaffargaon","গফরগাঁও",["Gafargaon"],"upazila"],
[472,62,"Ishwarganj","ঈশ্বরগঞ্জ",["Iswarganj"],"upazila"],
[473,62,"Nandail","নান্দাইল",[],"upazila"],
[474,62,"Tarakanda","তারাকান্দা",[],"upazila"],
[475,63,"Jamalpur Sadar","জামালপুর সদর",[],"upazila"],
[476,63,"Melandah","মেলান্দহ",[],"upazila"],
[477,63,"Islampur","ইসলামপুর",[],"upazila"],
[478,63,"Dewanganj","দেওয়ানগঞ্জ",["Dewangonj"],"upazila"],
[479,63,"Sarishabari","সরিষাবাড়ী",[],"upazila"],
[480,63,"Madarganj","মাদারগঞ্জ",[],"upazila"],
[481,63,"Bakshiganj","বকশীগঞ্জ",["Bokshiganj"],"upazila"],
[482,64,"Barhatta","বারহাট্টা",[],"upazila"],
[483,64,"Durgapur","দুর্গাপুর",[],"upazila"],
[484,64,"Kendua","কেন্দুয়া",[],"upazila"],
[485,64,"Atpara","আটপাড়া",[],"upazila"],
[486,64,"Madan","মদন",[],"upazila"],
[487,64,"Khaliajuri","খালিয়াজুরী",[],"upazila"],
[488,64,"Kalmakanda","কলমাকান্দা",[],"upazila"],
[489,64,"Mohanganj","মোহনগঞ্জ",["Mohongonj"],"upazila"],
[490,64,"Purbadhala","পূর্বধলা",[],"upazila"],
[491,64,"Netrokona Sadar","নেত্রকোণা সদর",[],"upazila"],
[492,9,"Eidgaon","ঈদগাঁও",[],"upazila"],
[493,39,"Madhyanagar","মধ্যনগর",[],"upazila"],
[494,50,"Dasar","ডাসার",[],"upazila"],
[1001,47,"Adabor",null,[],"thana"],
[1002,47,"Airport",null,["Bimanbandar"],"thana"],
[1003,47,"Badda",null,[],"thana"],
[1004,47,"Banani",null,[],"thana"],
[1005,47,"Bangshal",null,[],"thana"],
[1006,47,"Bhashantek",null,[],"thana"],
[1007,47,"Cantonment",null,["Dhaka Cantonment"],"thana"],
[1008,47,"Chawkbazar",null,["Chackbazar","Chowkbazar"],"thana"],
[1009,47,"Dakshinkhan",null,["Dakshin Khan"],"thana"],
[1010,47,"Darus Salam",null,["Darus-Salam"],"thana"],
[1011,47,"Demra",null,[],"thana"],
[1012,47,"Dhanmondi",null,[],"thana"],
[1013,47,"Gendaria",null,["Gandaria"],"thana"],
[1014,47,"Gulshan",null,[],"thana"],
[1015,47,"Hatirjheel",null,[],"thana"],
[1016,47,"Hazaribagh",null,[],"thana"],
[1017,47,"Jatrabari",null,["Jattrabari"],"thana"],
[1018,47,"Kadamtali",null,["Kadamtoli"],"thana"],
[1019,47,"Kafrul",null,[],"thana"],
[1020,47,"Kalabagan",null,[],"thana"],
[1021,47,"Kamrangirchar",null,[],"thana"],
[1022,47,"Khilgaon",null,[],"thana"],
[1023,47,"Khilkhet",null,[],"thana"],
[1024,47,"Kotwali",null,[],"thana"],
[1025,47,"Lalbagh",null,[],"thana"],
[1026,47,"Mirpur",null,["Mirpur Model"],"thana"],
[1027,47,"Mohammadpur",null,[],"thana"],
[1028,47,"Motijheel",null,[],"thana"],
[1029,47,"Mugda",null,[],"thana"],
[1030,47,"New Market",null,[],"thana"],
[1031,47,"Pallabi",null,[],"thana"],
[1032,47,"Paltan",null,["Paltan Model"],"thana"],
[1033,47,"Ramna",null,["Ramna Model"],"thana"],
[1034,47,"Rampura",null,[],"thana"],
[1035,47,"Rupnagar",null,[],"thana"],
[1036,47,"Sabujbagh",null,["Sabujbag"],"thana"],
[1037,47,"Shah Ali",null,[],"thana"],
[1038,47,"Shahbagh",null,["Shahbag"],"thana"],
[1039,47,"Shahjahanpur",null,[],"thana"],
[1040,47,"Sher-e-Bangla Nagar",null,["Sher e Bangla Nagar","Agargaon"],"thana"],
[1041,47,"Shyampur",null,[],"thana"],
[1042,47,"Sutrapur",null,[],"thana"],
[1043,47,"Tejgaon",null,[],"thana"],
[1044,47,"Tejgaon Industrial Area",null,["Tejgaon Industrial"],"thana"],
[1045,47,"Turag",null,[],"thana"],
[1046,47,"Uttarkhan",null,["Uttar Khan"],"thana"],
[1047,47,"Uttara East",null,[],"thana"],
[1048,47,"Uttara West",null,[],"thana"],
[1049,47,"Vatara",null,["Bhatara"],"thana"],
[1050,47,"Wari",null,[],"thana"]
]$json$::jsonb) r;


-- Ids came with the data; new rows carry on after them.
select setval(pg_get_serial_sequence('public.bd_divisions', 'id'), (select max(id) from public.bd_divisions));
select setval(pg_get_serial_sequence('public.bd_districts', 'id'), (select max(id) from public.bd_districts));
select setval(pg_get_serial_sequence('public.bd_upazilas', 'id'), (select max(id) from public.bd_upazilas));

-- ------------------------------------------------------------- matching ---

-- "Cox's Bazar", "Coxs Bazar" and "coxsbazar" are one place: lower case,
-- nothing but letters and digits.
create function public.bd_norm(p text)
returns text
language sql
immutable
set search_path = ''
as $$
  select nullif(lower(regexp_replace(coalesce(p, ''), '[^[:alnum:]]+', '', 'g')), '')
$$;

-- Does typed text name this place — by its name, its Bangla name, or any alias?
create function public.bd_matches(p text, p_name text, p_bn_name text, p_aliases text[])
returns boolean
language sql
immutable
set search_path = ''
as $$
  select public.bd_norm(p) is not null and (
    public.bd_norm(p) = public.bd_norm(p_name)
    or public.bd_norm(p) = public.bd_norm(p_bn_name)
    or exists (select 1 from unnest(p_aliases) a where public.bd_norm(a) = public.bd_norm(p))
  )
$$;

-- --------------------------------------------------------------- tenants ---
-- A hospital's or chamber's division, district and subdistrict stay text —
-- every form and the doctors_public view read them as text — but they are
-- written in the tables' spelling. "Comilla" is saved as "Cumilla"; a known
-- district fills in its division; an upazila found in only one district
-- fills in both. Text that matches nothing is kept as typed.

create function public.tenants_bd_canonical()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_division public.bd_divisions%rowtype;
  v_district public.bd_districts%rowtype;
  v_upazila  public.bd_upazilas%rowtype;
begin
  if new.district is not null then
    select * into v_district from public.bd_districts d
     where public.bd_matches(new.district, d.name, d.bn_name, d.aliases)
     limit 1;
  end if;

  if new.subdistrict is not null then
    if v_district.id is not null then
      select * into v_upazila from public.bd_upazilas u
       where u.district_id = v_district.id
         and public.bd_matches(new.subdistrict, u.name, u.bn_name, u.aliases)
       limit 1;
    elsif new.district is null then
      select * into v_upazila from public.bd_upazilas u
       where public.bd_matches(new.subdistrict, u.name, u.bn_name, u.aliases)
         and (select count(*) from public.bd_upazilas x
               where public.bd_matches(new.subdistrict, x.name, x.bn_name, x.aliases)) = 1;
      if v_upazila.id is not null then
        select * into v_district from public.bd_districts where id = v_upazila.district_id;
      end if;
    end if;
  end if;

  if v_district.id is not null then
    new.district := v_district.name;
    select * into v_division from public.bd_divisions where id = v_district.division_id;
    new.division := v_division.name;
  elsif new.division is not null then
    select * into v_division from public.bd_divisions dv
     where public.bd_matches(new.division, dv.name, dv.bn_name, dv.aliases)
     limit 1;
    if v_division.id is not null then
      new.division := v_division.name;
    end if;
  end if;

  if v_upazila.id is not null then
    new.subdistrict := v_upazila.name;
  end if;

  return new;
end
$$;

create trigger tenants_bd_canonical
  before insert or update of division, district, subdistrict on public.tenants
  for each row execute function public.tenants_bd_canonical();

-- What's already saved. Many hospitals only wrote "Bogura, Bangladesh" in
-- their location: its first part names the district.
update public.tenants t
   set district = btrim(split_part(t.location, ',', 1))
 where t.district is null
   and exists (select 1 from public.bd_districts d
                where public.bd_matches(split_part(t.location, ',', 1), d.name, d.bn_name, d.aliases));

-- A chamber at "Dhanmondi" in Dhaka: that part names the upazila or thana.
update public.tenants t
   set subdistrict = btrim(split_part(t.location, ',', 1))
 where t.subdistrict is null
   and exists (select 1 from public.bd_upazilas u
                where public.bd_matches(split_part(t.location, ',', 1), u.name, u.bn_name, u.aliases)
                  and (t.district is null
                       or u.district_id = (select d.id from public.bd_districts d where d.name = t.district)));

-- And every other saved spelling put right.
update public.tenants
   set district = district
 where division is not null or district is not null or subdistrict is not null;
